### ISSUE TITLE
Publication date of notice

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#103]
The Publication data I take it will be in the metadata and not the content of the Notice.  However the ontology sees it in the Notice class.  Since the PPDS needs the Publication Date maybe we should add it in the mapping?

**Comment by costezki** [comment]
Related to #118

**Comment by andreea-pasare** [comment]
An `epo:Notice` has attribute `epo:hasPublicationDate`.

![image](https://user-images.githubusercontent.com/88081600/189855405-97640d71-74f8-4a04-a533-8f934a389e7d.png)

**Comment by csnyulas** [comment]
![image](https://user-images.githubusercontent.com/2441046/219327446-22402a48-e8b8-4a61-9332-43680eb736b7.png)

**Comment by csnyulas** [comment]
Closing this issue as it has been fixed as suggested both in the technical mapping (see referenced commits) as well as in the conceptual mapping (v6.6.5), where we also added a note about the additional steps to be taken.
