### ISSUE TITLE
1.1.delta: Conceptual Mappings: Section IV: conceptual mapping

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#110]
I do not understand row 85 of excel file.
This section is about the procedure why do we have hasScopeDividedIntoLots  by definition all procedures have at least one lot according to the ontology

**Comment by costezki** [comment]
Agree, it was wrongly placed in the CM. The mapping was moved to Section II.2.

In RML mappings, it is correct, however. 

![image](https://user-images.githubusercontent.com/13567133/188898791-14507d46-3905-434b-93fa-3c33040c40c6.png)

**Comment by muricna** [comment]
ok I understand it provides a list of lots associated to the procedure and just one if there is only one lot
