### ISSUE TITLE
x1.1.delta: Conceptual Mappings - Section V.2.4

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#113]
The total value of the contract is mapped to (example 163-2021)
  epo:Tender / epo:MonetaryValue / xsd:decimal | ?this epo:hasFinnancialOfferValue /   epo:hasAmountValue ?value .
-- | --

The lowest offer and the highest offer taken into consideration are mapped to ( example 2750-2021)

epo:SubmissionStatisticalInformation / MonetaryValue /   xsd:decimal | ?this   epo:hasLowestReceivedTenderValue / epo:hasAmountValue ?value .
-- | --

I have some concerns about the usage of Tender here, especially if negotiations are involved.  In the case of the total value in the best case scenario one could argue that the tender value has changed but we have a temporal problem here.  However taking the LowestReceivedTenderValue from the SubmissionStatisticalInformation does not seem correct.

**Comment by costezki** [comment]
Related to #116 #113.

**Comment by costezki** [comment]
![image](https://user-images.githubusercontent.com/13567133/188892967-dbdb8afb-b6ab-45a8-a74f-20093b9accd0.png)

**Comment by costezki** [comment]
![image](https://user-images.githubusercontent.com/13567133/189305569-11ae81f6-5597-4aaf-9f2a-c89e30d74266.png)

**Comment by andreea-pasare** [comment]
Decided to use `epo:hasAwardedValue` predicate from `epo:LotAwardOutcome` to `epo:MonetaryValue`. 
Similar solution for #127.

**Comment by muricna** [comment]
The lowest and highest offers appear to be mapped correctly however the contract/lot total value has to be mapped as described above

**Comment by csnyulas** [comment]
Closing as it is fixed, together with #127. For further info, see [these closing remarks](https://github.com/OP-TED/ted-rdf-mapping/issues/127#issuecomment-1302764736).
