### ISSUE TITLE
x1.1.delta: Conceptual Mappings - Section VI.I.4.3 : Precise information on deadlines for review procedures.

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#115]
The mapping for this element in the excel is:

epo:Lot   / epo:ReviewTerm | ?this   epo:isSubjectToLotSpecificTerm / epo:hasReviewDeadlineInformation ?value .
-- | --

However in the ontology I see:  

![image](https://user-images.githubusercontent.com/26601116/185935514-ddce39b6-f165-47d0-a02b-1c502ed81141.png)

I think this section is at Procedure level the mapping indicates it but the ontology indicates at lot level.  If this is at lot level is then repeated in each lot?

</body>

</html>

**Comment by costezki** [comment]
Note "Section VI.I.4.3 : Precise information on deadlines for review procedures" does not exist, we corrected to `VI.4.3`

This is related to #130 

![image](https://user-images.githubusercontent.com/13567133/188888631-b2d9b5e2-0ea2-4ac3-a427-9359fbe62b69.png)
