### ISSUE TITLE
x1.1.delta: Consider including the Notice ID in the rdf directly not via the metadata (PPDS request)

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#118]

**Comment by costezki** [comment]
This will be considered in the future.

**Comment by andreea-pasare** [comment]
![image](https://user-images.githubusercontent.com/88081600/189855755-8ddc042a-2e8a-46e8-b302-96e8605b3932.png)

**Comment by csnyulas** [comment]
Closing this as it has been addressed while fixing #342. For more comments, and related commits, check out that issue. 

For reference, this is how the Notice IDs are now attached to the notice:

![image](https://user-images.githubusercontent.com/2441046/219247913-9cb53735-6ce1-433e-b577-a7971245637a.png)
