### ISSUE TITLE
x1.1.delta: Conceptual Mappings: Section II.2.4 description of the procurement

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#120]
In the excel the mapping is Lot hasDescription.

However it is missing in the rdf see example 
348503-2021

**Comment by costezki** [comment]
A lot needs to have a short description. 
Mapping missing. 

![image](https://user-images.githubusercontent.com/13567133/188879383-0661a9cc-068b-4af0-ba77-030ce9fd546f.png)

**Comment by csnyulas** [comment]
Can be checked with the following SPARQL query:
```SPARQL
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
SELECT * {
  ?s epo:hasDescription ?o.
  ?s a epo:Lot.
}
```

**Comment by muricna** [comment]
In 366836-2021 the content in the RDF does not match the content in the xml.  I tried to find the content that is in the RDF in the xml but this produced no Result.
