### ISSUE TITLE
x1.1.delta: Conceptual Mappings: Section II.2.5.3.1 has formula

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#121]
Although the rdf gives the correct weighting the excel file shows cccev:name instead of cccev: weight

**Comment by costezki** [comment]
We will make the updates in the CM file.

**Comment by costezki** [comment]
Price has no name but can have weight. 

![image](https://user-images.githubusercontent.com/13567133/188877304-0fba107d-a2c9-41f4-b3db-ad0607cb95aa.png)
