### ISSUE TITLE
x1.1.delta: Conceptual Mappings: Section II.2.14 Additional information

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#122]
Data missing in rdf see example 348503-2021

**Comment by costezki** [comment]
Note: Section II.2.1.4 does not exist, we will consider that you mean II.2.14. 

We will add the mapping for the additional information property. 



![image](https://user-images.githubusercontent.com/13567133/188873521-8909bc29-76c6-4dbb-b12b-d1dabe582eb3.png)
![image](https://user-images.githubusercontent.com/13567133/188873836-1d370700-d75f-46b3-9a7c-790f17b10d8a.png)
