### ISSUE TITLE
x1.1.delta: Conceptual Mappings: Section IV.2.9 Information about termination of call for competition in the form of a prior information notice

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#124]
When this field is empty in the xml it cannot have a boolean of false in the rdf see 163-2021

**Comment by costezki** [comment]
The section reference is IV.2.9, not II.2.9.
We will provide true, if element exists and we will provide noting when the element is missing

![image](https://user-images.githubusercontent.com/13567133/188862760-0fe84e70-9730-4bcb-8746-41ffd5735a5b.png)
