### ISSUE TITLE
tx1.1.delta: Conceptual Mappings: Section VI.4.1 Review body Contact point internet address  

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#129]
There is an inconsistency here the Review body hasPrimaryContactPoint is missing from 348503-2021 and therefore the internet address is missing however the hasPrimaryContactPoint is present in 163-2021 maybe due to it having other elements and not just the internet address.

**Comment by csnyulas** [comment]
We can close this ticket as this has been fixed.
See, for example, the screenshot of the generated `348503-2021.ttl`
![image](https://user-images.githubusercontent.com/2441046/193430313-16f9a636-928f-4c5f-94ef-4a8e31f18740.png)

Also, by running this SPARQL query on the generated triples, we can see all the `cpov:ContactPoint` instances, and we can observe that all of them are linked to a another instance, and they may have different details attached, including cases where there is only the `cpov:hasInternetAddress` is provided:

```SPARQL
SELECT ?stype ?s ?p_scp ?cp ?p ?o {
  ?cp ?p ?o.
  ?cp a cpov:ContactPoint.
  
  OPTIONAL {
    ?s ?p_scp ?cp.
    ?s a ?stype.
  }
}
ORDER BY DESC(?cp) DESC(?p)

```
