### ISSUE TITLE
tx1.1.delta: Conceptual Mappings: Section VI.4.2 Review Procedure

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#130]
Why is ReviewTerm a LotSpecificTerm?Is this due to eForms if this is the case is it repeated for each lot in the rdf for the current forms?

**Comment by muricna** [comment]
By checking 19698-2021 that has many lots this is mapped to every lot

**Comment by csnyulas** [comment]
This is an interesting question to be discussed in the working group meeting.

**Comment by costezki** [comment]
We provide a ReviewTerm for each lot, even if the review term in StandardForms is given only once at the procedure level.
