### ISSUE TITLE
tx1.1.delta: RDF: 348503-2021 why does the predicate hasReservedAppicability appear

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#131]
This concept is found under hasContractSpecificTerm and relates to an authority list not listed in transformation resources.  it is visble in other lots as well of other notices

**Comment by costezki** [comment]
![image](https://user-images.githubusercontent.com/13567133/187693660-0f682f47-5f78-40a2-953f-31b27e15eb62.png)
