### ISSUE TITLE
tx1.1.delta: RDF: 337360-2021missing II.2.1 although implemented correctly in 348503

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#132]

**Comment by costezki** [comment]
There is a title and description of the procedure, and the lot does not have any. 
This is the case in the XML data both: for 337360 and for 348503. 
The RDF data reflects what is in XML accurately. 

Possibly for the procedures with a single Lot, we could take the title & description from the Procedure and put it on the Lot.  This is, however, discouraged.
