### ISSUE TITLE
tx1.1.delta: Conceptual Mappings: Section V.2.2.1-V.2.2.6 no link between the statistical information and the lots

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#134]
The mapping has SubmissionStatisticalInformation should be associated to each lot which is not the case see for example 19698-2021

**Comment by costezki** [comment]
It appears to be a BUG in `tedm:SubmissionStatisticalInformation` triplemap.

![image](https://user-images.githubusercontent.com/13567133/188192086-8e25758b-ad2b-4a06-97c8-0b4a964e44c7.png)

**Comment by costezki** [comment]
In the XML there are only 6 `<tenders>` elements, and therefore we have only 6 `SubmissionStatisticalInformation` yet there are 8 Lots in total. So 2 do not have corresponding data in the input XML.

**Comment by costezki** [comment]
We will fix the connection from the SubmissionStatisticalInformation to the corresponding Lot.

**Comment by csnyulas** [comment]
This has been fixed in technical mapping (see related commits). In the conceptual mapping the link between the `epo:Lot` and the `epo:SubmissionStatisticalInformation` instances is done at level of the `V.2.2 - Information about tenders` field.
