### ISSUE TITLE
tx1.1.delta: V.2.4.1 Initial estimated total value of the contract not instantiated when more than one lot.

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#136]
See 19698-2021.
This could be due to the fact that the winner is associated to a tender rather than lot it is possible to provide the winner from the lot rather than the tender (which should probably not be instatiated in the notice as the notice does not mention a tender or tenderer). See association of lot and winner (via LotAwardOutcome) in the diagram below:

![image](https://user-images.githubusercontent.com/26601116/187539953-78a793d9-bf53-44f7-8026-2622edc0c2df.png)

**Comment by csnyulas** [comment]
See initial comments in https://docs.google.com/document/d/1ZbNc9PcYs09DENcUcLMgk3szePJAjXHaXldPjwJDMB4/edit?disco=AAAAfZlcbMc

**Comment by costezki** [comment]
The current mapping is aligned to the ontology. 
We can discuss how the lot, award outcome and winner be linked in the ontology working group. 
The mapping can be adapted once a decission is taken.

**Comment by costezki** [comment]
The MonetaryValue instances are created, but they are not linked to anything.
Review join condition between Lot and MonetaryValueLot in section 5.

![image](https://user-images.githubusercontent.com/13567133/188605000-be1db802-0aa4-4fb1-bfaf-d714a9acc90d.png)
![image](https://user-images.githubusercontent.com/13567133/188605131-a6952c9b-be3e-462f-861e-ef483ab520fb.png)
![image](https://user-images.githubusercontent.com/13567133/188605248-5a1bc2f3-aae6-4e31-a667-8b34d650eb80.png)
![image](https://user-images.githubusercontent.com/13567133/188605335-c991a079-999a-46a0-bab3-0ae7df29ccc0.png)

**Comment by muricna** [comment]
Becarefule there are several monetary values in the notices and sometimes the values are the same even if the concept they are related to are different
