### ISSUE TITLE
tx1.1.delta:  excel row 119 and 120 should be more explicit on the use of winner-selection-status

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#137]
Before finding LotAwardOutcome the usage of this authority table and how to describe the award or not of a contract was not clear

**Comment by costezki** [comment]
Please use the section numbers/IDs (available in Column A) for reference rather than the row number for higher precision.

**Comment by costezki** [comment]
The line `V.0.6` will be split into two to make it clearer how the mapping conditions work.

**Comment by csnyulas** [comment]
We fixed this issue by splitting conceptual mapping of field "A contract/lot is awarded" (now `V.0.4`) into two separate rows, with separate XPaths and separate mappings. Validation tests look good.
We will wait for (potential) feedback before we close this issue.
