### ISSUE TITLE
tx1.1delta In 131568: Lots 4 and 5 are not awarded however there is a LotAwardOutcome indicating winner selected and association with a tender with a financial offer

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#141]
<http://data.europa.eu/a4g/resource/LotAwardOutcome/2021-S-052-131568/a5941b75-32bc-31c2-a76d-5d5d8bda3d9f>
  a epo:LotAwardOutcome;
  epo:comprisesTenderAwardOutcome <http://data.europa.eu/a4g/resource/TenderAwardOutcome/2021-S-052-131568/a586ea4c-6836-37c0-99f5-aa2a3e69d886>;
  **epo:describesLot <http://data.europa.eu/a4g/resource/Lot/2021-S-052-131568/a7bff5a3-ac28-3c67-b4c6-67f990704217>;**
  **epo:hasAwardStatus <http://publications.europa.eu/resource/authority/winner-selection-status/selec-w> .**

<http://data.europa.eu/a4g/resource/Lot/2021-S-052-131568/a7bff5a3-ac28-3c67-b4c6-67f990704217>
  a epo:Lot;
  epo:hasID <**http://data.europa.eu/a4g/resource/LotIdentifier/2021-S-052-131568/a7bff5a3-ac28-3c67-b4c6-67f990704217>**;

http://data.europa.eu/a4g/resource/LotIdentifier/2021-S-052-131568/a7bff5a3-ac28-3c67-b4c6-67f990704217>
  a epo:Identifier;
  epo:hasIdentifierValue "5" .

There seems to be a muddle in the non-awarded lots when there is more than one lot

**Comment by costezki** [comment]
This is related to #142 .

**Comment by costezki** [comment]
![image](https://user-images.githubusercontent.com/13567133/188653375-4625014b-e9d9-4f55-bcad-d920ff54cc50.png)
![image](https://user-images.githubusercontent.com/13567133/188653491-666312e2-e7b6-4ce4-99c2-cb76d581d9cb.png)

**Comment by csnyulas** [comment]
See final closing comment on issue #142, which describes the solution provided: https://github.com/OP-TED/ted-rdf-mapping/issues/142#issuecomment-1248001495

**Note:** There is a mistake in the title of the issue: The lots that were not awarded are **lot nr 1** (referred by contract no 4) and **lot nr 5**  (referred by contract no 5), not lot numbers 4 and 5.

We opened a related issue #164, to clarify what should be done with contract that were not awarded.

**Comment by muricna** [comment]
I don't understand why we talk about Contract 4 and Contract 5 the xml does not foresee any Contract numbers
