### ISSUE TITLE
tx1.1delta Section II.2.5 Award criteria missing in rdf of 29476-2022

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#143]

**Comment by csnyulas** [comment]
This appears when the award criteria element is empty, i.e. does not contain any sub-elements, such as “AC_CRITERION” or “AC_WEIGHTING”. Such cases appear in the following files in our sample data (we have examples only for the AC_PRICE element, but theoretically it also could appear for AC_QUALITY or AC_COST):

```
002705-2021.xml:<AC_PRICE/>
006737-2021.xml:<AC_PRICE/>
029476-2021.xml:<AC_PRICE/>
029476-2021.xml:<AC_PRICE/>
042126-2021.xml:<AC_PRICE/>
160659-2021.xml:<AC_PRICE/>
183277-2021.xml:<AC_PRICE/>
234762-2021.xml:<AC_PRICE/>
270899-2021.xml:<AC_PRICE/>
292288-2021.xml:<AC_PRICE/>
292288-2021.xml:<AC_PRICE/>
292288-2021.xml:<AC_PRICE/>
292288-2021.xml:<AC_PRICE/>
300414-2021.xml:<AC_PRICE/>
358415-2022.xml:<AC_PRICE/>
358415-2022.xml:<AC_PRICE/>
377668-2021.xml:<AC_PRICE/>
431462-2021.xml:<AC_PRICE/>
431462-2021.xml:<AC_PRICE/>
431462-2021.xml:<AC_PRICE/>
503174-2021.xml:<AC_PRICE/>
661127-2021.xml:<AC_PRICE/>
663165-2021.xml:<AC_PRICE/>
Command: grep -o -E "<AC_[^/>]+/>" *
```

Please see comments in the F03 conceptual mapping file:
https://docs.google.com/spreadsheets/d/1Ma2-TG-F3RwuGJElGwYiLL34ftJxmkrrHgHPOt6Qx7o/edit#gid=435265674&range=E69
https://docs.google.com/spreadsheets/d/1Ma2-TG-F3RwuGJElGwYiLL34ftJxmkrrHgHPOt6Qx7o/edit#gid=435265674&range=E76

**Solution:** remove the conditions from the subject mapping in the technical mapping files:
`exists(AC_CRITERION) or exists(AC_WEIGHTING))`
