### ISSUE TITLE
tx1.1delta Section VI.3 Additional Information exists twice in both EN and IT in 29476-2021

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#144]

**Comment by costezki** [comment]
Handle multiple languages for 

Section VI.3 Additional Information
COMPLEMENTARY_INFO/INFO_ADD

Language tags appear wrongly

![image](https://user-images.githubusercontent.com/13567133/188595023-6f70a9d2-6bf2-4c44-855d-dcb39e7faa92.png)
