### ISSUE TITLE
tx1.1delta Section 1.  instead of using the role buyer the role central purchasing body has been used in 214679

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#145]
The xml notice indicates buyer so the rdf should use the role buyer even if it can be implied by the fact that the procedure is awarded by a cpb.  This is a case when there is only one buyer but if there were several buyers then you could not infer that all buyers were cpbs.

This will also complicate querying

**Comment by costezki** [comment]
Solution: 
Instances of epo:AwardingCentralPurchasingBody will also be instances of Buyer.

**Comment by costezki** [comment]
![image](https://user-images.githubusercontent.com/13567133/189310681-e1f87d6e-ecad-43af-89e4-32a19591dd0c.png)

**Comment by fokoug** [comment]
I put all rr:class epo:AwardingCentralPurchasingBody in comment and I add rr:class epo:Buyer

**Comment by csnyulas** [comment]
Closing this issue, as it has been fixed.
The relevant row has been removed from the conceptual mapping, and the subject map was changed in the technical mapping to not use the `epo:AwardingCentralPurchasingBody` type for "SME buyers" anymore.

The following SPARQL query return no results (while it returned threeresults in tag `tx1.1.delta`):
```SPARQL
SELECT ?s ?p ?o 
{ ?s a epo:AwardingCentralPurchasingBody. }
```
