### ISSUE TITLE
tx1.1delta 214679-2021 Internet address of winner missing

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#148]

**Comment by fokoug** [comment]
The report show that there are internet address in this file but a text search with "Internet Address" in the file shows nothing.  
![Screenshot 2022-09-05 at 22 11 15](https://user-images.githubusercontent.com/24571803/188508820-50e5d353-b5c0-4e2c-b29f-51aedb7411b1.png)
![Screenshot 2022-09-05 at 22 10 44](https://user-images.githubusercontent.com/24571803/188508833-33d6cfe7-90e1-4537-9337-ced24b76a8f2.png)

**Comment by costezki** [comment]
We will fix the mapping of V.2.3.10

`AWARD_CONTRACT/AWARDED_CONTRACT/CONTRACTORS/CONTRACTOR/ADDRESS_CONTRACTOR/URL`
