### ISSUE TITLE
tx1.1delta: RDF sample missing V.2.4.3-V.2.4.5

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#150]
See example 2705-2021
Even if the content was in the SubmissionStatisticalInformation until the SubmissionStatiticalInformation is associated to the lot this mapping cannot work see [github-134](https://github.com/OP-TED/ted-rdf-mapping/issues/134).

Further more the v3.0 of the ontology does not foresee: hasLowestReceivedTenderValue and hasHightestReceivedTenderValue in the SubmissionStatisticalInformation.  Even if it existed it needs to be ensured that section II (procedure level) and section V (contract level) can be taken into consideration.

**Comment by costezki** [comment]
SubmissionStatisticalInformation works on the Lot level (Section V) and epo:NoticeAwardInformation works at the Procedure level (Section II). Both convey statistical information about monetary values. 

![image](https://user-images.githubusercontent.com/13567133/188194947-a04f5059-911b-45e8-b193-690a7810449f.png)
![image](https://user-images.githubusercontent.com/13567133/188195099-f36722b1-d65e-4636-b8ab-44b59e282ad1.png)

**Comment by costezki** [comment]
We will fix missing hasLowestReceivedTenderValue and hasHighestReceivedTenderValue award info on 
epo:NoticeAwardInformation and epo:SubmissionStatisticalInformation .

**Comment by csnyulas** [comment]
This has been fixed, and can be also tested with the following SPARQL query:
```SPARQL
SELECT ?stype ?s ?p_scp ?cp ?p ?o {
  ?cp ?p ?o.
  ?cp a epo:SubmissionStatisticalInformation.
  
  OPTIONAL {
    ?cp ?p_scp ?o.
    ?o a ?stype.
  }
}
ORDER BY DESC(?cp) DESC(?p)
```
