### ISSUE TITLE
two agents for one role (winner) instance in 214679 notice

### ISSUE THREAD

**Issue by costezki** [OP-TED/ted-rdf-mapping#152]
Related to #148 

![image](https://user-images.githubusercontent.com/13567133/188223292-418011ec-9fb3-4732-b402-9eba1d47ed53.png)

**Comment by fokoug** [comment]
This is bug is the result of this Mapping rule:
![Screenshot 2022-09-05 at 21 29 08](https://user-images.githubusercontent.com/24571803/188505405-131f169b-6033-4053-84b4-288a1c5275be.png)

In fact, it is the  same  contractor that we found only once in test-data search with official name Acciona Construcción, S. A.
![Screenshot 2022-09-05 at 21 37 35](https://user-images.githubusercontent.com/24571803/188506017-03528652-8b56-434a-8f0a-129a92a49884.png)
 
But the mapping create two instances of two different classes :
![Screenshot 2022-09-05 at 21 43 58](https://user-images.githubusercontent.com/24571803/188506443-ac4b3f53-e999-4365-950b-28a585dfbbe8.png)

and 
![Screenshot 2022-09-05 at 21 45 18](https://user-images.githubusercontent.com/24571803/188506538-a0595412-e020-49a0-b6d7-bb4c2bfeb22b.png)

And moreover, the mapping with epo:hasBusinessSize appear only once in the conceptual Mapping
<img width="1285" alt="Screenshot 2022-09-05 at 21 25 32" src="https://user-images.githubusercontent.com/24571803/188505125-9debb87c-b947-4756-a600-a04538aca901.png">

This conceptual Mapping rule looks like it is not well transform in technical Mapping, mainly transformation of the "Field XPath condition (M)" (if(exists(.)) then 'true' else 'false'). I think false means no need to create instance.

**Comment by idellal** [comment]
The conceptual/technical mappings are good. Let's see what can we use as predicate/class instead of playedByBusiness/Business to describe this information.

**Comment by costezki** [comment]
@idellal
1 let's use "played by" relation
2 there cannot be 2 organisations referred to from one instance of a role. 

So there shall either be 2 instances of a role or the agent shall be the same.

**Comment by andreea-pasare** [comment]
`at-voc:economic-operator-size` is linked to `epo:Business`. 

We should either:
1. change the source class from `epo:Business` to `epo:Organization` for `epo:hasBusinessSize` predicate in ePO 
OR
3. add `epo:Business` as an additional type of the ContractOrganization instance in the mapping
![image](https://user-images.githubusercontent.com/88081600/189847914-ce4f155e-3154-48e5-a8c1-b6b2c18ee410.png)

**Comment by muricna** [comment]
An organisation is not necessarily a business so I am not for choice 1.  As for 2 I do not know what a Contract Organization is so I cannot comment.

**Comment by csnyulas** [comment]
At the WG meeting we decided to go for option 2 mentioned by @andreea-pasare, that if the SME checkbox is checked we will "reuse" the Organization instance, and we will add `epo:Business` as an additional type

**Comment by csnyulas** [comment]
Closing this as the fix has been implemented as we agreed.

Run the following SPARQL query to see the outcome of this fix:
```SPARQL
SELECT ?roletype ?role ?s ?type 
{ ?s a epo:Business . 
 ?s a ?type.
 OPTIONAL {?role epo:playedBy ?s. 
           ?role a ?roletype.
 }
}
```
