### ISSUE TITLE
fix section II.2.11 OPTIONS/NO_OPTIONS

### ISSUE THREAD

**Issue by costezki** [OP-TED/ted-rdf-mapping#153]
Will Fix, creating ContractTerm, indicating NO options. 
In CM this is the rule  II.2.11 (BT-53) 

Example 214679-2021

-----

For the third rule Options, with XPath OBJECT_CONTRACT/OBJECT_DESCR/OPTIONS we don't have tag OPTIONS

Concerning options this is part of another question but if there are no options we need to indicate "no" ie a false boolean.

----

Related to #146 

![image](https://user-images.githubusercontent.com/13567133/188588871-8c06d93e-e87d-4a0d-885f-636d933d3b77.png)

**Comment by csnyulas** [comment]
Closing this, as it is fixed.
Run this query to see how the `epo:hasOptions` values are mapped:
```SPARQL
SELECT ?ms ?p ?s ?o 
{ ?s epo:hasOptions ?o . 
 ?ms ?p ?s.
}
ORDER BY ?ms ?s
```
