### ISSUE TITLE
NO-SME: V.2.3.12 conceptual and technical mapping

### ISSUE THREAD

**Issue by costezki** [OP-TED/ted-rdf-mapping#156]
![image](https://user-images.githubusercontent.com/13567133/188861318-d961c46e-7e23-4be5-92f0-e6f40f05e6ff.png)
![image](https://user-images.githubusercontent.com/13567133/188861331-58c549d4-6805-4db9-85b1-9c5c511e4728.png)

In case of `NO_SME` XML element is present, shall we map the value to `economic-operator-size:large` ???

https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/economic-operator-size

Related to #126

**Comment by csnyulas** [comment]
This issue can be closed as we agreed that the current representation is the best that we can do.

We also decided to document such cases explicitly (see issue #191).
