### ISSUE TITLE
not all CPV codes appear in the RDF. 

### ISSUE THREAD

**Issue by costezki** [OP-TED/ted-rdf-mapping#157]
![image](https://user-images.githubusercontent.com/13567133/188882651-80b5f474-afa6-4bff-9ce1-ecf2554af848.png)

One of the two codes at the LOT (purpose) level does not appear in the RDF file. 

![image](https://user-images.githubusercontent.com/13567133/188882877-5d2f2207-036a-426b-a11c-d704e6d23b2d.png)

**Comment by costezki** [comment]
Related #119

**Comment by csnyulas** [comment]
The following SPARQL query demonstrates that multiple CPV codes are added to Lots where it is needed, and would also be added to Procedures, but we don't have such cases in our sample (including from the supplementary CPV codes vocabulary for the `CPV_ADDITIONAL` elements):

```SPARQL
#SELECT ?atype ?a ?ap ?stype ?s ?p ?cpv
SELECT (SAMPLE(?atype) AS ?atype) (SAMPLE(?a) AS ?a) (SAMPLE(?ap) AS ?ap) 
   (SAMPLE(?stype) AS ?stype) ?s (SAMPLE(?p) AS ?p) 
   (COUNT(?cpv) AS ?cpvCount) (GROUP_CONCAT(?cpv) AS ?cpvList)
{
 ?s ?p ?cpv.
  OPTIONAL { ?s a ?stype}
  OPTIONAL {?a ?ap ?s.
            OPTIONAL {?a a ?atype}
           }
  FILTER(?p IN (epo:hasMainClassification, epo:hasAdditionalClassification))
  FILTER(?ap IN (epo:hasOverallPurpose, epo:hasPurpose))
}
GROUP BY ?s  #comment out this line if you'd like to run the non-grouping select 
ORDER BY ?s
```
