### ISSUE TITLE
Do not instantiate Tenderer

### ISSUE THREAD

**Issue by costezki** [OP-TED/ted-rdf-mapping#159]
Comment out this role. 

![image](https://user-images.githubusercontent.com/13567133/189150429-d5b48dc8-0edd-4565-a61c-83d014ce6812.png)

**Comment by csnyulas** [comment]
This simple SPARQL query demonstrates that there are no instances of `epo:Tenderer` generated anymore.
```
SELECT ?s
{
 ?s a epo:Tenderer.
}
```
Note: the same query returned 59 instances before the the fix was implemented.
