### ISSUE TITLE
Bring non existence query to bring in Mapping with condition (if)

### ISSUE THREAD

**Issue by fokoug** [OP-TED/ted-rdf-mapping#175]
![Screenshot 2022-09-19 at 13 55 21](https://user-images.githubusercontent.com/24571803/191011706-6fe1092a-82e2-4e4d-b64b-7f7903d7e47d.png)
when XPATH exist it means it is covered and the SPARQL query ASK {?this epo:foreseesContractSpecificTerm / epo:hasOptions ?value } will return true (?value=true).
But in the case when XPATH doesn't exist, it means it is nor covered but  the SPARQL query ASK {?this epo:foreseesContractSpecificTerm / epo:hasOptions ?value } will still return true because ?value=false.

try to bring non existence query to more precise the query report.

**Comment by csnyulas** [comment]
These cases are marked as a "Warning", which is an acceptable solution (a half "Fix"), but we should discuss if there are no better solutions that can be implemented.
