### ISSUE TITLE
Make sure that *:Nuts@code is interpretable byXML engine

### ISSUE THREAD

**Issue by fokoug** [OP-TED/ted-rdf-mapping#178]
Make sure that *:Nuts@code is interpretable byXML engine, because all the XPATH with Make sure that *:Nuts@code is interpretable byXML engine are marked as not coverage but we could find them in other XPATH existing in the file.

**Comment by csnyulas** [comment]
We fixed this by removing the prefixes (`*:`) of the XML elements representing the NUTS codes in the "Field XPath (M)" column and added the correct and complete XPath (with the prefix) to the "Field XPath condition (M)" column. The indexer was also updated by @kaleanych to remove the prefixes from the XML elements when creating the index.
With this double approach we have successfully eliminated the related missing XPath and invalid SPARQL query results from the validation reports.
