### ISSUE TITLE
CA_TYPE_OTHER doesn't map into RDF even if the XPATH is in Conceptual mapping

### ISSUE THREAD

**Issue by fokoug** [OP-TED/ted-rdf-mapping#198]
In 148511-2021.XML we found 
```
<CA_TYPE_OTHER>
 SCI dont l'associé principal est une SA d'HLM
</CA_TYPE_OTHER>
``` 
but this value is not map into RDF even if the path /TED_EXPORT/FORM_SECTION/F03_2014/CONTRACTING_BODY/CA_TYPE_OTHER is Map in conceptual. mapping.

**Comment by csnyulas** [comment]
Here is a simple SPARQL query that shows that the issue has been fixed:
```
SELECT ?s ?p ?o 
{ ?s epo:hasBuyerLegalTypeDescription ?o . }
```
