### ISSUE TITLE
CA_ACTIVITY_OTHER doesn't map into RDF even if the XPATH is in Conceptual mapping

### ISSUE THREAD

**Issue by fokoug** [OP-TED/ted-rdf-mapping#199]
In 046890-2021.XML we found 
```
<CA_ACTIVITY_OTHER>
  Autre — eau, assainissement, déchets ménagers, voirie, transports collectifs, aménagement urbain
</CA_ACTIVITY_OTHER>
```
 but this value is not map into RDF even if the path /TED_EXPORT/FORM_SECTION/F03_2014/CONTRACTING_BODY/CA_ACTIVITY_OTHER is Map in conceptual. mapping.

**Comment by csnyulas** [comment]
Here is a simple SPARQL query that shows that the issue has been fixed:
```
SELECT ?s ?p ?o 
{ ?s epo:hasMainActivityDescription ?o . }
```
