### ISSUE TITLE
Rename `epo:hasBuyerType` to `epo:hasBuyerLegalType` and `epo:hasMainActivityType` to `epo:hasMainActivity`

### ISSUE THREAD

**Issue by csnyulas** [OP-TED/ted-rdf-mapping#200]
`epo:hasBuyerType` will be renamed to `epo:hasBuyerLegalType` in next version (3.0.1 ???) of ePO.
Also `epo:hasMainActivityType` will be renamed to `epo:hasMainActivity`. 
The renaming are necessary to reduce ambiguity and possible confusion.

When we decide to update the mappings to the new version of ePO **conceptual and technical mappings should be updated**.

**Comment by muricna** [comment]
Issue to be transferred to epo github

**Comment by csnyulas** [comment]
Closing this issue as it has been fixed both in the conceptual mapping (starting with v.26.2.0) and in the technical mapping (see referenced commits above).
