### ISSUE TITLE
Is there any special semantics for repeating CPV codes for the same Lot or Procedure in XML ?

### ISSUE THREAD

**Issue by csnyulas** [OP-TED/ted-rdf-mapping#205]
We found the following example in the `366836-2021.xml` file.

![image](https://user-images.githubusercontent.com/2441046/193428638-f58bce30-c69a-44c9-b158-b04d05ffd611.png)

For this Lot we create the a `epo:LotPurpose` instance with the following CPV codes:
![image](https://user-images.githubusercontent.com/2441046/193428763-953a2379-9237-4635-9153-5038643f6dc1.png)

This oks like exactly how it is supposed to be represented in RDF. However, it would be nice if @muricna, @andreea-pasare or someone with in-depth knowledge of ePO and the TED notice encoding could confirm this.

**Comment by costezki** [comment]
The supplementary needs to be associated with the “normal” CPV. This association is not supported in the EPO, and it is not foreseen to be supported in the future.  Therefore, the mapping to supplementary CPV is dropped forever. In the CM we just make a remark that it is NOT mapped. Nothing is done in the Output.
