### ISSUE TITLE
F03: Inconsistencies of the generated RDF w.r.t. the ontology 

### ISSUE THREAD

**Issue by dachafra** [OP-TED/ted-rdf-mapping#212]
We have analyzed the generated RDF of F03 w.r.t. the ontology (OWL files, not UML) and we've found the following inconsistencies:  

- [x] `epo:ProcedureSpecificTerm` class: The RDF contains instances of the class `epo:ProcedureSpecificTerm` with values for the properties `epo:hasCrossBorderLaw` and `epo:isAwardedByCPB`. But this class is superclass of `epo:ProcedureTerm` and these properties have `epo:ProcedureTerm` as the domain, so it's not correct to assign these properties to a superclass.
- [x] `epo:BuyerProfile` class has instances in the RDF, but it does not exist in the ontology (if it is in the UML we will transfer this issue to the ontology repo)
- [x] `https://www.w3.org/ns/legal#registeredAddress` property from `org:Organization` and `epo:Business` is a non-maintained vocabulary (and it redirects to `https://www.w3.org/ns/legal-entity` which is also non-maintained). 
- [x]  `epo:includesLotAwardOutcome` as a property of `epo:Contract` but is not included in the ontology (if it is in the UML we will transfer this issue to the ontology repo)
- [x] Boolean literals are missing their datatype (`"false"^^xsd:boolean`)
- [x] The objects from the property `epo:hasDispatchDate` from the class `epo:ResultNotice` which should be a `xsd:date` are now a plain literal

**Comment by dachafra** [comment]
Point two has been solved (issue updated). 
@costezki @csnyulas please if you solve some of the issues described here it would be great if you can also update this issue to let us know that they are being corrected, thanks :-)!

**Comment by muricna** [comment]
Boolean false information is missing because they do not exist in the data source

**Comment by costezki** [comment]
@dachafra, we have fixed some of the missing datatypes in the mappings. That will be published in the next mappings release.

**Comment by dachafra** [comment]
Thanks, @costezki, booleans are not super relevant right now, but in the case of `dates` if we do not have the datatype, the SPARQL queries in virtuoso used for calculating the indicators are extremely slow!

**Comment by costezki** [comment]
Dates have been addressed too

**Comment by dachafra** [comment]
marked as resolved above then, many thanks!

**Comment by muricna** [comment]
epo:includesLotAwardOutcome as a property of epo:Contract but is not included in the ontology does not exist and should not exist the mappings need to be corrected to epo:Contract epo:resultsFromLotAwardOutcome

**Comment by guascce** [comment]
We cannot avoid that data might be missing or wrongly entered as the Forms do not have rules about all information elements that are needed to compute indicators. In a further future, when designing new statistical objects to answer upcoming analytical needs, the principle that decouples the rules to apply before statistics are measured with the Forms/eForms seems necessary as the eForms are ruled by legislation while the statistical objects are (up to my knowledge ) designed on an operational ground (see PPDS governance).
Aside from the mistakes of the ontology or its wrong instantiation , this pleads for an application profile. See issue

**Comment by csnyulas** [comment]
The second bullet point was indeed a mistake (EPO has been changed after the original mappings were done, and the mappings were not updated to conform to the EPO changes), and we have ficed it as part of issue #327

**Comment by costezki** [comment]
Point 1 refers to #312 
Point 3 refers to #301 
Point 4 refers to #263

**Comment by csnyulas** [comment]
Point 4 was resolved in #329. Closing this as all tasks have been addressed.
