### ISSUE TITLE
V.1.1.3: Why is there a mapping to this in the excel I do not think it appears in the schema

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#228]

**Comment by valexande** [comment]
I will close this issue as it seems obselete. We do have this mapping in our TM.

For example Iook at the figure below where the mapping exists in the ttl file of F06 notice 198522-2021

![1](https://github.com/OP-TED/ted-rdf-mapping/assets/53187315/5b67a237-ae63-46f5-8340-17a896540c17)
