### ISSUE TITLE
tx1-2: rename Technique classes to contain "-usage" suffix

### ISSUE THREAD

**Issue by costezki** [OP-TED/ted-rdf-mapping#241]
![image](https://user-images.githubusercontent.com/13567133/203521819-2f6d349e-7316-4233-b23c-83726ac0b70f.png)

**Comment by fokoug** [comment]
Update EAuctionTechnique in s4_procedure.rml.ttl, technical_mapping_F03.rml.ttl, technical_mapping_F06.rml.ttl, technical_mapping_F13.rml.ttl, technical_mapping_F20.rml.ttl, technical_mapping_F21.rml.ttl, technical_mapping_F22.rml.ttl, technical_mapping_F23.rml.ttl and technical_mapping_F25.rml.ttl.

**Comment by csnyulas** [comment]
Closing this as it can also be seen in the latest commit on the generated F06 output (8bc11398264ac2d418719460c38b170b316088c1) or more clearly in earlier commits of the generated output, such as https://github.com/OP-TED/ted-rdf-mapping/commit/982be7a9cccf2f9a5b9a37489d465f4af3afb801#diff-8bb59f477ab8e9d3693ce24c0d2d83fe7eb2f5bdfbd7ad0c579e92620d876c3e
