### ISSUE TITLE
tx1-2: submission language is missing

### ISSUE THREAD

**Issue by costezki** [OP-TED/ted-rdf-mapping#250]
> IV.2.4 Concept is missing from 459484-2021

To be investigated, why this rule does not fire. 

![image](https://user-images.githubusercontent.com/13567133/203578531-bc114838-944b-4bcb-a43a-9933b75edc8f.png)
![image](https://user-images.githubusercontent.com/13567133/203578615-9d81f7a1-6262-476b-9c15-4ce3a4fb29b4.png)

**Comment by fokoug** [comment]
I complete the XPath, now it is fix.
![Screenshot 2022-11-24 at 23 44 51](https://user-images.githubusercontent.com/24571803/203871443-a00ea80d-8ef7-483e-8093-b108beb92a52.png)
![Screenshot 2022-11-24 at 23 44 35](https://user-images.githubusercontent.com/24571803/203871449-c644b685-7c73-4415-af81-82abdf469f75.png)

**Comment by csnyulas** [comment]
Relevant entry in the conceptual master conceptual mapping was also updated, starting with version 4.1.0.

**Comment by csnyulas** [comment]
Closing this issue as it was fixed. See references from commits above.
