### ISSUE TITLE
tx1-2: mapping ProcurementProcedureInformationProvider role

### ISSUE THREAD

**Issue by costezki** [OP-TED/ted-rdf-mapping#251]
Context F21 
> I.3.3.1  No mapping there should be a mapping to the address of the buyer as the ProcurementProcedureInformationProvider for this row

> 1.3.3.2.12.2 Although the xml may foresee that the ProcurementProcedureInformationProvider can have a BuyerProfile this is not possible in the RDF, since the BuyerProfile is a property of the Buyer.  The example of an ProcurementProcedureInformationProvider having a BuyerProfile is when the Buyer is the ProcurementProcedureInformationProvider 

See: 407866-2021

**Comment by csnyulas** [comment]
Closing this ticket as it was split into #258 and #259
