### ISSUE TITLE
tx1-2: mapping the delivery channel

### ISSUE THREAD

**Issue by costezki** [OP-TED/ted-rdf-mapping#252]
context F21

> 1.3.4.1-I.3.4.3 Mapping is missing is missing (See 407866-2021 for 1.3.4.1 and 1.3.4.3)(See 601542-2021 for 1.3.4.2)

> 1.3.5: The mapping has Delivery Gateway however it would also be possible to map through Procedure usesChannel Channel hasAdhocURL .  See: 601452-2021

The ontology needs to have only one of these paths and the mapping needs to respect that path. Three paths are currently possible. (one on Organisation - deliveryGateway, one on the Procedure, one in the Submission term; the latter is recommended to be used)
* 

![image](https://user-images.githubusercontent.com/13567133/203585202-75c6a8e0-f2b7-4a1e-a172-28469d5669ce.png)
![image](https://user-images.githubusercontent.com/13567133/203585506-98c5f7aa-ebc9-4da4-abb3-333b99a417f4.png)

**Comment by andreea-pasare** [comment]
Section 1.3.4 should be handled similarly to Section 1.3.3. But we need a Role that should be linked to the Organization that is mentioned. ePO provides 2 different roles for participation request receiving and tenders receiving:
![image](https://user-images.githubusercontent.com/88081600/204829377-a0026d0b-e641-497b-9a88-6d0991720a6c.png)

**Comment by csnyulas** [comment]
We decided to use the `epo:TenderReceiver` role for mapping the field I.3.4 "Tenders or requests to participate must be submitted" (in particular its subfields I.3.4.2. and I.3.4.3).

![image](https://user-images.githubusercontent.com/2441046/204902721-1b84f813-5aa3-4cb7-adc0-85469b117916.png)

**Comment by csnyulas** [comment]
The second part of the issue, regarding the mapping of the field 1.3.5, will be dealt with in a separate issue: #256 .

**Comment by muricna** [comment]
TenderReceiver does not exist in the rdf  for 601452-2021 and 78258-2021 although the information is available in the xml

**Comment by csnyulas** [comment]
Closing this issue as it was resolved in tx1.3 (see above referenced commits from Dec. 6 and 7), and the solution is still there in tag `tx1.4.beta`.

The referenced commit above, about the generated output, shows clearly that the TenderReceiver instance is being created both for [601452-2021](https://github.com/OP-TED/ted-rdf-mapping/commit/798bf074198b2d8caf4f0d5459a55968bd425e21#diff-4b047e7289d0af08bfc19a1996afea4096205a7d888b1e5a4c48ed3be1df9f5c) and [78258-2021](https://github.com/OP-TED/ted-rdf-mapping/commit/798bf074198b2d8caf4f0d5459a55968bd425e21#diff-eab85789b085d5ee6b41a12690a9499b33cd214fccdd11ffa80e0e1e64deb21a).

And here are the relevant lines in `tx.1.4-beta` for **078258-2021**

https://github.com/OP-TED/ted-rdf-mapping/blob/3c0d4fb7706a991650ac056aba0a9418fb0f9a78/mappings/package_F21/output/078258-2021/078258-2021.ttl#L245-L263

and for **601452-2021**

https://github.com/OP-TED/ted-rdf-mapping/blob/3c0d4fb7706a991650ac056aba0a9418fb0f9a78/mappings/package_F21/output/601452-2021/601452-2021.ttl#L179-L181
