### ISSUE TITLE
tx1-2: Delete redundant rows in conceptual mappings for fields IV.1.1.1 and IV.1.1.2 in form F25

### ISSUE THREAD

**Issue by csnyulas** [OP-TED/ted-rdf-mapping#255]
Context: Feedback on F25 mappings 

> IV.1.1 This does not seem mappable procurement-procedure-type in EUVocabularies does not foresee this concept.  Any suggested solution is welcome.This line seems to be repeated in the conceptual model (2 rows below)

> IV.1.2 This does not seem mappable procurement-procedure-type in EUVocabularies does not foresee this concept.  Any suggested solution is welcome.This line seems to be repeated in the conceptual model (2 rows below)

![image](https://user-images.githubusercontent.com/2441046/204797795-f1812e38-5a11-49c9-9fe6-1faa1c40d9b7.png)

Note: This issue concerns only the duplicated rows in the conceptual mappings. For the first part of the observations there is a separate issue opened on the ePO project: https://github.com/OP-TED/ePO/issues/424

**Comment by csnyulas** [comment]
Fixed (i.e. extra rows were deleted) in version 4.1.0 of conceptual mapping.

**Comment by csnyulas** [comment]
Closing issue, as the CM containing the fix was committed in package_F25.

**Comment by muricna** [comment]
19.	IV.1.1.1: A message has been sent to GROW, their interim solution is to map to procurement-procedure-type open.
20.	IV.1.1.2: A message has been sent to GROW, their interim solution is to map to procurement-procedure-type neg-wo-call.
