### ISSUE TITLE
Tx1-2: Mapping of field I.3.5 Electronic communication... (URL)

### ISSUE THREAD

**Issue by csnyulas** [OP-TED/ted-rdf-mapping#256]
context F21

> 1.3.5: The mapping has Delivery Gateway however it would also be possible to map through Procedure usesChannel Channel hasAdhocURL .  See: 601452-2021

![image](https://user-images.githubusercontent.com/2441046/204843368-75c6c187-b39b-473e-b0b8-e8296f390508.png)

Should be changed to:

![image](https://user-images.githubusercontent.com/2441046/204843887-9753351c-036e-4293-b9fa-b26d14acbc31.png)

**Comment by csnyulas** [comment]
Fixed in CM version 3.5.0

**Comment by csnyulas** [comment]
This issue has been fixed as proposed (i.e. by linking the Channel to the Procedure, instead of the Organization). However, I would not close this issue until it is confirmed that this will remain the final solution, by considering the following questions/potential problems:

**Questions:** 
- What happens if there are multiple `CONTRACTING_BODY/URL_TOOL` paths in the data? Which one should be linked to the Procedure? Or should we link multiple channels to the Procedure? Which one is the "good" one? We haven't found such data in our testing sample (except once, see below), but according to the XSD such situation can arrise, and would be valid. The only place where we have multiple `URL_TOOL` elements is in notice 357454-2021.xml (which is an F08 form in the `sampling_2014_2022/R2.0.9.S04.E01` folder), but here the URLs are on different root elements, where one is the translation of the other.
- What happens in standard form F08 (and potentially F14), where we can have `URL_TOOL` on the Buyer organization, but we don't have Section IV, for Procedure? (e.g. 172624-2021.xml) 

Hopefully @muricna or @andreea-pasare or @costezki can help answering the above questions.

**Comment by muricna** [comment]
If the hasAdhocURL is used for this mapping then there is no problem for other URLs.
F08 does have a section for procedures see: Section II.1
If it is not clear that section II.1 is for procedure and II.2 for lot in all forms maybe we need a meeting to explain the forms

**Comment by muricna** [comment]
Why has the ADhocURL not been used as requested?

**Comment by costezki** [comment]
We seem to be missing the above stated solution of connecting the Channel to the Procedure. (e.g. 601452-2021)

![image](https://user-images.githubusercontent.com/13567133/215999764-1f574b26-688f-4908-bfcc-3b1d982b03d6.png)
![image](https://user-images.githubusercontent.com/13567133/216000114-bd6acedf-da0d-4871-8d1a-532fb5d5e1f7.png)

**Comment by costezki** [comment]
After having a discussion in eOrdering the WG realised and decided that a channel shall be linked to the Organisation (or rather it's Role). So, it appears that the original mapping of section I.3.5 of delivery Channel to Organisation was correct.

**Comment by csnyulas** [comment]
In fact, we did some improvements. As it can be seen in the referenced commits, we have:
- renamed the TriplesMap (from `tedm:OrganisationChannel` to `tedm:ElectronicCommunicationChannel`) to avoid any possible confusion;
- removed the `epo:hasDeliveryGateway` gateway to this Channel from the BuyerOrganisationGroup, which was left there probably due to an oversight, when the channel was attached to the Procedure
- set the `epo:isAdhocChannel` property value for this Channel to `true`.

**Comment by muricna** [comment]
The conceptual mapping file needs to be updated to reflect this update that the epo:isAdhocChannel is used.
