### ISSUE TITLE
Issues with mapping of section I.3.1 

### ISSUE THREAD

**Issue by csnyulas** [OP-TED/ted-rdf-mapping#257]
There seem to be  couple issues with the way sub-section I.3.1 is mapped:
- To what should `epo:AccessTerm` instance be linked? Should be the `epo:Procedure` instance?
- Do we need to instantiate `epo:ProcurementDocument`? It does not seem to be used (i.e. contain any additional information)

![image](https://user-images.githubusercontent.com/2441046/204839919-f1fa9b80-8b06-4eb7-8245-531aca2ea9fb.png)

**Comment by csnyulas** [comment]
The solution we decided to implement is to link the AccessTerm to the Procedure
![image](https://user-images.githubusercontent.com/2441046/204896713-a7981aae-c953-4198-a390-2d2b303f249a.png)

For this to be correct `epo:AccessTerm` needs to become a subclass `epo:ProcedureSpecificTerm`.

**Comment by csnyulas** [comment]
Fixed in CM version 4.1.0. Technical mapping needs to be implemented.

**Comment by csnyulas** [comment]
Question: What happens in standard form F08, where we have section I.3 Communication, but we don't have Section IV, for Procedure?

**Comment by csnyulas** [comment]
Marked this as fixes, but not closing it yet, as the above question should be still answered. Hopefully @muricna or @andreea-pasare or @costezki can help with that.

**Comment by muricna** [comment]
In tx1-2 gamma, although the conceptual mapping for section I.3 goes through Procedure  in the rdf the path is through lot

**Comment by csnyulas** [comment]
This has been validated together with @muricna and @costezki in the `tx1.4.beta` tag output.

**Comment by csnyulas** [comment]
Closing this issue as the solution for this (i.e. that the `epo:AccessTerm` instance is always linked to the Procedure) was implemented in tx1.3 and and it is still there in tag `tx1.4.beta`.
