### ISSUE TITLE
tx1-2: Mapping of field 1.3.3.2.12.2 might not be necessary

### ISSUE THREAD

**Issue by csnyulas** [OP-TED/ted-rdf-mapping#259]
Context F21 

[Comment from N Muric]
> 1.3.3.2.12.2 Although the xml may foresee that the ProcurementProcedureInformationProvider can have a BuyerProfile this is not possible in the RDF, since the BuyerProfile is a property of the Buyer.  The example of an ProcurementProcedureInformationProvider having a BuyerProfile is when the Buyer is the ProcurementProcedureInformationProvider 

See: **407866-2021**

Further comments:
>How does the InformationProvider have a BuyerProfile the BuyerProfile is a propery of Buyer.  In this case 407866-2021 the BuyerProfile comes from the fact that the AgentInRoles are the same.

Current mapping:
![image](https://user-images.githubusercontent.com/2441046/204918436-7f9f31e4-a20d-46c4-b16f-213857ffa636.png)

**Comment by csnyulas** [comment]
@muricna We need to decide together what is the best way to deal with this.

On one hand it is easy to drop this mapping (or move it to the "Mapping Remarks" sheet). This will result in some additional warnings in the XPATH validation reports (i.e. this XPATH will be reported as an unmapped).

On the other hand, my understanding is that the RDF representation should be a faithful representation of what is in the XML data. Dropping certain XML elements (such as `URL_BUYER`) would result in an incomplete representation of the XML data in RDF. Also, it is worth noting that this information could be useful (or even critical) for recognizing identical (`owl:sameAs`) `epo:Organization` instances in the deduplication process.

BTW, in case the field I.3.3.1 "The above mentioned address" (XPATH `CONTRACTING_BODY/ADDRESS_FURTHER_INFO_IDEM`) is checked we will reuse the Organization that plays the `epo:Buyer` role to play also the `epo:ProcurementProcedureInformationProvider` role. Wouldn't we be in this case also in the same undesirable situation that the organization that plays the `epo:ProcurementProcedureInformationProvider` role has a BuyerProfile with some information, such as the URL? In principle can't *any* organization have a BuyerProfile, even if in a certain situation it plays a different role (such as `epo:ProcurementProcedureInformationProvider` or `epo:TenderReceiver`) that does not require/processes such information?

Idea: Is there another property that we could use to map the information in the `URL_BUYER` element in case of a `epo:ProcurementProcedureInformationProvider` role?

**Comment by muricna** [comment]
I would suggest adding a remark that this is not mappable as the Ontology only foresees to the BuyerProfile as a property of Buyer.

**Comment by csnyulas** [comment]
Closing this, as has been fixed as proposed by @muricna , i.e. we removed the unnecessary mappings in the TM and CM, and made notes in the "Mapping Remarks" sheet of the CM of forms F21, F22 and F23, that this information is not mappable to EPO.

![image](https://user-images.githubusercontent.com/2441046/215454338-d4129d54-3e2d-4996-9255-e219ddb99778.png)
