### ISSUE TITLE
xsd:date vs. xsd:datetime

### ISSUE THREAD

**Issue by csnyulas** [OP-TED/ted-rdf-mapping#269]
Why do we use in some places `xsd:date` and in other places `xsd:datetime` to represent various dates that appear in the notices? Are they so declared in ePO? If yes, why? Can not it be made consistent overall? 

Whatever the case is in ePO, we should make sure that the mappings are reflecting properly, everywhere, the types declared in ePO.

**Comment by csnyulas** [comment]
Currently the mappings use `xsd:date` for mapping the following XPaths:
`AWARDED_CONTRACT/DATE_CONCLUSION_CONTRACT`, `AWARDED_PRIZE/DATE_DECISION_JURY`, and (in issue #262) it was suggested that we use it for `DATE_PUBLICATION_NOTICE` as well.

**Comment by andreea-pasare** [comment]
`xsd:datetime` is used only when it is required to also provide the time in hh:mm:ss. 
For example, `epo:hasOpeningDateTime` attribute on the concept `epo:OpeningTerm` has the following definition:
 _Date and **time** for the opening of tenders. WG Approval 12/03/2019_

**Comment by csnyulas** [comment]
The following data types are used in ePO:
- `xsd:dateTime` for `epo:hasBeginning` and `epo:hasEnd` (on the `epo:Period` class) - **already correct** in CM and TM
- `xsd:dateTime` for `epo:hasReceiptDeadline` (on the `epo:SubmissionTerm` class) - **already correct** in CM and TM
- `xsd:dateTime` for `epo:hasReceiptExpressionsDeadline` (on the `epo:SubmissionTerm` class) - **already correct** in CM and TM
- `xsd:dateTime` for `` (on the `` class) - **already correct** in CM and TM

and
- `xsd:date` for `epo:hasEstimatedContractNoticePublicationDate` (on the `epo:ProcessPlanningTerm` class) - **to be fixed** in CM and TM (used to be `xsd:datetime`)
- `xsd:date` for  `epo:hasContractConclusionDate` (on the `epo:Contract` class) - **to be fixed** in CM (used to be `rdf:langString`), **already correct** in TM
- `xsd:date` for  `epo:hasAwardDecisionDate` (on the `epo:LotAwardOutcome` class) - **to be fixed** in CM (used to be `rdf:langString`), **already correct** in TM
- `xsd:date` for `epo:hasDispatchDate` (on the `epo:Notice` class) -  **to be added** in CM and TM (type is missing)
- `xsd:date` for `epo:hasAwardDateScheduled` (on the `epo:ProcessPlanningTerm` class) - **to be added** to CM and TM, if confirmed as the correct solution for issue #270 (currently no mapping)
