### ISSUE TITLE
Conceptual model to show Procedure hasLegalBasis

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#290]
The conceptual model shows hasLegalBasis with no path though Procedure although the output shows this

**Comment by csnyulas** [comment]
This information has been added at some point as the very first row of the conceptual mapping, with the Field Id called "MetaData", to each form (except for F13, by omission, which has been fixed in v.6.1.2 of the CM, which will be delivered in TX1.4). See screenshot below:

![image](https://user-images.githubusercontent.com/2441046/213800269-4ee92d1e-41de-4740-a74d-2af366ee7ddd.png)

We mark this issue as Fixed. If this solution is satisfactory please close the ticket. Otherwise we will close it ourselves if there will be no additional feedback within a few days.

**Comment by csnyulas** [comment]
Here is a related question to this issue: 
Currently we map the value of the `VALUE` attribute of the `LEGAL_BASIS` XML element. In recent XSD versions, there is also a `LEGAL_BASIS_OTHER` XML element for most (and perhaps all) forms.
**Is there anything to be done to map the value of the  `LEGAL_BASIS_OTHER` XML element?**

**Comment by csnyulas** [comment]
Second question: 
**Should the `hasLegalBasis` property be attached to the Procedure instance(s) (as it is now), or to the Notice instance?**

**Comment by csnyulas** [comment]
Decision after discussing the issue with @muricna and @costezki:
`epo:hasLegalBasis` property takes as a value an IRI from the `at-voc:legal-basis` vocabulary, based on the value of the `LEGAL_BASIS` XML element. The values in `LEGAL_BASIS_OTHER` are of type free text (not controlled in any way), therefore they cannot be mapped to `epo:hasLegalBasis` property. EPO needs to be extended to allow for the representation of the values in the `LEGAL_BASIS_OTHER` XML elements. Also, we might want to be able to state information about the legal basis at Procedure level and at document level separately (although with containing the same value), for which we might need to add yet another property in EPO.

For now we will need to make a note in the conceptual mapping stating that the value of the `LEGAL_BASIS_OTHER` XML element is not going to be mapped until appropriate support for it is provided in EPO. We can do that on the "Mapping Remarks" sheet or in the Notes column of the Rules sheet .

**Comment by csnyulas** [comment]
A note about not being able to map `LEGAL_BASIS_OTHER`, yet, has been added to the CM, v.6.4.1 (see latest linked commit)

![image](https://user-images.githubusercontent.com/2441046/215879109-5b838ae0-0ffe-496f-9fb0-277c6ba71ac5.png)

We can close this issue as soon as the still open question(s), i.e. the mapping of `LEGAL_BASIS_OTHER`, and (potentially) what is the best place to attach `epo:hasLegalBasis` (see https://github.com/OP-TED/ted-rdf-mapping/issues/290#issuecomment-1399046160), have been recorded as issue(s) on the EPO project.

**Comment by csnyulas** [comment]
Closing this issue, as the two outstanding questions have been recorded as separate issues:
https://github.com/OP-TED/ePO/issues/448 and https://github.com/OP-TED/ted-rdf-mapping/issues/422
