### ISSUE TITLE
Throughout the mapping: Contract "resultsFromLotAwardOutcome" not "includesLotAwardOutcome" 

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#295]
The mapping and therefore the rdf to be updated to follow the ontology ie Contract resultsFromLotAwardOutcome should be used as per the ontology

Furthermore in F22 for section V row 184 there is the comment:
Probably the Contract shall be used for Title and Identifier, the rest shall be on the Lot Award Outcome.
This is for ePO V3.0.1. In a future version the Contract will change and evolve significantly.
Eugen & Andreea 2022-11-18
This comment is only in F22 and should be removed and maybe inserted in the comments.  Becareful with this comment if there is no award of contract then no contract title can be given this has to be discussed when changes are considered.

**Comment by costezki** [comment]
Lets update the name of the property.

![image](https://user-images.githubusercontent.com/13567133/216009986-e4ab952f-de8c-4612-b241-2772bb421acf.png)

**Comment by csnyulas** [comment]
Closing this as it has been resolved in duplicate issue #329. For details on solution, see related commits there.
