### ISSUE TITLE
III.1.4.1 Rules and criteria for participation

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#297]
NM comment: 22/11/2022
III.1.4.1 This is not about selection criteria as shown in the mapping but about the rules and criteria for participation

This has not been addressed in TX1-2gamma.  A suggestion would be:

III.1.4.1 It would maybe better to map to the cccev: Requirement as this covers more than just the selection criterion as reflected in the mappings.  This would require a link between the procedure and requirement.

**Comment by costezki** [comment]
This is not mappable to EPO 3.1.0. In the CM this will be signalled accordingly. 

In the future mapping done to a future ontology version this will be mapped appropriately.

**Comment by csnyulas** [comment]
Marking this as **addressed**, as the temporary solution, for EPO 3.1.0, was implemented both in CM and TM (i.e. no mapping is being done until new version of EPO does not provide appropriate model for these fields). For more, see comments and referenced commits.

We should **close this issue only after** a final solution has been implemented.
