### ISSUE TITLE
Procedure level not lot level

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#298]
NM comment 22/11/2022:
III.1.5.1-III.2.3.1 and all intermediary rows are at Procedure level not Lot level this is the particularity of the current forms as opposed to eForms.  Therefore other elements of these fields have not been considered.

Comment 19/01/2023
See 497881-2021 (F21)
III.1.5.1 and III.1.5.3 As these fields are not lot specific it might be better to move the authority table to the upper level ProcurementElement so it can be reused in Contract if necessary

**Comment by muricna** [comment]
See also F22  III.1.5.2 and III.2.2 

See for example 528848-2021 which has 6 lots but this section is not about the individual lots

**Comment by costezki** [comment]
This is not mappable to EPO 3.1.0. In the CM this will be signalled accordingly.

In the future, mapping done to a future ontology version this will be mapped appropriately.

Duplicated by #297

**Comment by csnyulas** [comment]
Marking this as **addressed**, as the temporary solution, for EPO 3.1.0, was implemented both in CM and TM (i.e. no mapping is being done until new version of EPO does not provide appropriate model for these fields). For more, see comments and referenced commits.

We should **close this issue only after** a final solution has been implemented.
