### ISSUE TITLE
20.	IV.2.5 No mapping, no example of this element

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#299]
Comment of 22/11/2022
IV.2.5 No mapping, no example of this element

Suggestion 19/01/22
See 34993-2021 (F21)
If the ontology does not cover this a remark should be made and a request made to the ontology to discuss and cover this

**Comment by costezki** [comment]
Related to #270.

This mapping cannot be established to ePO v3.1.0 because the coresponding property is missing in the ontology. 

"that" property is not suitable. 

![image](https://user-images.githubusercontent.com/13567133/216080709-9091381c-7070-47bc-9098-333feb1b8dec.png)

**Comment by csnyulas** [comment]
This was implemented in issue #270 as it was suggested by those familiar with EPO:

See conceptual mapping:
![image](https://user-images.githubusercontent.com/2441046/219688502-2e9c252c-fd58-49b1-980f-e31e79d2381f.png)

technical mapping:
![image](https://user-images.githubusercontent.com/2441046/219690012-4ce998c0-2481-4b0a-9c67-0d608b021ae6.png)

and the current output of 
![image](https://user-images.githubusercontent.com/2441046/219690410-7ec08988-748a-476f-9d97-96e406448477.png)

Isn't this correct? If not, what should be the correct solution?

**Comment by costezki** [comment]
This is not mappable in EPO 3.1.0. It will be addressed in the 
https://github.com/OP-TED/ePO/issues/422

**Comment by csnyulas** [comment]
Addressed this by commenting out the related mapping in the technical mappings (see referenced commits above), and marking this field as not mappable to EPO 3.1.0 in the conceptual mapping (v.6.7.2).

![image](https://user-images.githubusercontent.com/2441046/219826775-21e99517-70b7-4a25-9b2d-5ccd15c1f85e.png)

We should **close this issue only after** a final solution has been implemented.
