### ISSUE TITLE
Organization is mapped to legal:registeredAddress whilst the ontology shows cv:registeredAddress

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#301]
The mapping and the rdf should be aligned with the ontology.  The alignment should be carried out in all forms and fields as necessary.

The legal:registeredAddress is used for Person not Organization. Comment to be carried to all cases with the same property path in all sections.  See also comment 212

**Comment by costezki** [comment]
Update the base URI of the property. 

![image](https://user-images.githubusercontent.com/13567133/216010644-4c56972f-1e0f-47d3-b34c-06db4a31f5d5.png)

**Comment by csnyulas** [comment]
Closing this as it has been addressed both in CM and TM in issue #334, where you can find further information and all the related commits.
