### ISSUE TITLE
Main place of performance is instantiated at Procedure level should only be at lot level

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#303]
II.2.3 MainPlaceOfPerformance is mapped at lot level corresponding to the notice however in the rdf it is present in both the lot and the Procedure.  It should not be mapped to the procecedure.
Example: 671859-2021

**Comment by costezki** [comment]
Some properties in the ContractTerm are specified at the Procedure Level and some properties in the ContractTerm are specified at the Lot level. 

Ideally, in the context of Standard Forms, we would create a separate mapping for the ContractTerm for Procedure and one for Lot. And the ContractTerm would have been instantiated differently depending where it comes from. 

Solution is splitting tedm:ContractTerm -> tedm:ContractTermLot + tedm:ContractTermProcedure. 

![image](https://user-images.githubusercontent.com/13567133/216011941-4bced7cc-8998-4de2-a5fd-a1d8dee9cfcd.png)

**Comment by csnyulas** [comment]
Closing this issue, as it has been addressed. See related commits.
