### ISSUE TITLE
TemporalUnit recommended in ontology does not exist

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#304]
II.2.7.1.1-II.2.7.1.2: The codelist TemporalUnit foreseen in the ontology does not exist should the ontology not use at-voc timeperiod?  If so create a ticket for the ontology and map already to this as what the ontology provides is only a reccommendation as it is how can we map to a code list that does not exist or does it?

**Comment by csnyulas** [comment]
The unit of the duration is provided in terms of `time:TemporalUnit` , which is defined by the `owl:time` ontology: https://www.w3.org/TR/owl-time/#time:TemporalUnit , not in any of the AT vocabularies. So, the mapping is correct. There is nothing to be done.
