### ISSUE TITLE
Time limit for receipt of tenders or requests to participate / Time limit for receipt of expressions of interest

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#305]
IV.2.2. The xpath has been mapped across to different elements in the ontology and the date put in hasRecieptDeadline? and the time in hasReceiptExpressionsDeadline.  Only one of the elements should be used and a remark created in the remarks sheet.
The ontology foresees Datatime however we cannot put a time if no time is indicated in the notice because it could be contradictory to procurement documents if we impose 00:00 for example.

Example: 528848-2021

**Comment by costezki** [comment]
1. Remove the logic of appending time segment when it is missing. 
2. Change the datatype from xsd:dateTime to xsd:date.
3. Add a "BIG RED banner" in the CM explicitly stating that we do not take the time into the consideration. 

![image](https://user-images.githubusercontent.com/13567133/216133806-41546dd7-5619-4f6b-a55f-d9d9b7967d27.png)

**Comment by csnyulas** [comment]
Addressed this in the technical mapping (see referenced commits), and also by adding explanatory notes in the conceptual mapping (v.6.7.3)

![image](https://user-images.githubusercontent.com/2441046/219845330-c18ff95e-d577-4808-b8eb-3db276b49334.png)
