### ISSUE TITLE
F22 III.1.9.1 and III.1.9.2 Not just about selection criteria

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#311]
NM comments 22/11/2022:

III.1.9.1 This is about conditions for a qualification system not selection criteria for a lot
III.1.9.2 This is about conditions for a qualification system not selection criteria for a lot

**Comment by csnyulas** [comment]
Marking this as **addressed**, as the temporary solution, for EPO 3.1.0, was implemented both in CM and TM (i.e. no mapping is being done until new version of EPO does not provide appropriate model for these fields). For more, see comments and referenced commits.

We should **close this issue only after** a final solution has been implemented.

**Comment by costezki** [comment]
This is further take in https://github.com/OP-TED/ePO/issues/423. This ticket can be closed.
