### ISSUE TITLE
I.2.2. Mapping of isAwardedByCPB to ProcedureSpecificTerm however the property is in ProcedureTerm in the ontology

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#312]

**Comment by costezki** [comment]
It appears that in TM there is `tedm:ProcedureTerm` and `tedm:ProcedureSpecificTerm`. They need to be merged into `tedm:ProcedureTerm`. 

both properties below are ProcedureTerm related. 

![image](https://user-images.githubusercontent.com/13567133/216024162-c8e9d01f-2dad-4235-afbe-3bf7ba5cb251.png)
