### ISSUE TITLE
I.6-1.6.1 MainActivity mapped through OrganisationGroup in case of joint procurement

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#313]
In F22 there is still a case of this being mapped via the individual buyers see: 557366-2021
In F06 it goes correctly through organisationGroup: 8380-2021

**Comment by costezki** [comment]
The mainActivityType is implemented correctly. It appears only ONCE in the OtrganisationGroup (when there is an organisation group). 

However, the mainActivityDEscription appears also, one more time in the "main" organisation of the group. And it should not. 

![image](https://user-images.githubusercontent.com/13567133/216025921-79e168e2-fca6-4984-ae7f-0c7afeb38de5.png)
![image](https://user-images.githubusercontent.com/13567133/216026262-75625b64-58e6-4dbf-8708-e362e8e75e8b.png)
![image](https://user-images.githubusercontent.com/13567133/216026297-dc3c627a-1f9b-4a4c-b1e3-42d9fd6acf62.png)

**Comment by csnyulas** [comment]
Addressed this issue by adding missing conditions to the mapping of the `epo:hasMainActivityDescription` property in the `tedm:Organisation` mapping. See related commits above.
