### ISSUE TITLE
III.2.1.1 Not about individual selection criterion

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#315]
III.2.1.1: This is not about an individual selection criterion nor about the suitability but the actual service being reserved to a particular profession

III.2.1.2: This is not about an individual selection criterion but the law associated the execution of the service by a given profession.

**Comment by costezki** [comment]
Related to #297 #298 

This is not mappable in EPO 3.1.0.

**Comment by csnyulas** [comment]
Marking this as **addressed**, as the temporary solution, for EPO 3.1.0, was implemented both in CM and TM (i.e. no mapping is being done until new version of EPO does not provide appropriate model for these fields). For more, see comments and referenced commits.

We should **close this issue only after** a final solution has been implemented.
