### ISSUE TITLE
III.2.3.1.  Not tender requirements

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#316]
III.2.3.1  There are 2 rows associated to this element:
The first row: Not sure why this is considered a tender requirement  it could be a participation or contract requirement.
The second row: This field seems unnecessary since there is no need to indicate non-existence

**Comment by costezki** [comment]
Related to #297 #299 

This is not mappable to EPO 3.1.0. In the CM this will be signalled accordingly.

In the future mapping done to a future ontology version this will be mapped appropriately.

**Comment by csnyulas** [comment]
Marking this as **addressed**, as the temporary solution, for EPO 3.1.0, was implemented both in CM and TM (i.e. no mapping is being done until new version of EPO does not provide appropriate model for these fields). For more, see comments and referenced commits.

We should **close this issue only after** a final solution has been implemented.
