### ISSUE TITLE
Field IV.2.2: Fix mapping of epo:hasReceiptDeadline and epo:hasReceiptExpressionDeadline

### ISSUE THREAD

**Issue by csnyulas** [OP-TED/ted-rdf-mapping#323]
Currently we map the value of `DATE_RECEIPT_TENDERS` to `epo:hasReceiptDeadline` and the value of `TIME_RECEIPT_TENDERS` to `epo:hasReceiptExpressionDeadline`. We discovered that this is inappropriate, thanks to the SHACL shape validation reporting a violation on the values of these properties, which should be `xsd:dateTime` according to EPO.

After discussing with @andreea-pasare, we identified that the correct mapping, in fact, would be to combine the value of `DATE_RECEIPT_TENDERS` and `TIME_RECEIPT_TENDERS` into one value (concatenating the value of `DATE_RECEIPT_TENDERS` with "T", then with the value of `TIME_RECEIPT_TENDERS`, and then with ":00"), and make it of type `xsd:dateTime`. The generated value should be mapped **either** through the property `epo:hasReceiptDeadline` **or** through the property `epo:hasReceiptExpressionDeadline` depending on the Form number and Notice type.

Looking at the questions in forms F21, F22 and F23, in order to identify the appropriate use of property based on the notice type, this is what we found:

Question IV.2.2) 
**in F21:**
Time limit for receipt of tenders or requests to participate <SUP>5</SUP>
<SUP>5</SUP> please provide this information if the notice is a _call for competition_
``` 
	<NOTICE TYPE="CONTRACT"/>
```	
Time limit for receipt of expressions of interest <SUP>14</SUP>
<SUP>14</SUP> if this is a _prior information notice used as call for competition_ – please provide this information as far as it is already known
```
	NOTICE TYPE="PRI_CALL_COMPETITION"
```

**in F22:**
Time limit for receipt of tenders or requests to participate <SUP>5</SUP>
<SUP>5</SUP> please provide this information if the notice is a _call for competition_
``` 
	<NOTICE TYPE="CONTRACT"/>
	<NOTICE TYPE="QSU_ONLY"/>
	<NOTICE TYPE="QSU_CALL_COMPETITION"/>
	<NOTICE TYPE="PER_ONLY"/>
	
```	
Time limit for receipt of expressions of interest <SUP>14</SUP>
<SUP>14</SUP> if this is a _periodic indicative notice used as call for competition_ – please provide this information as far as it is already known

```
	NOTICE TYPE="PER_CALL_COMPETITION"
```

**in F23:**
Time limit for submission of applications or receipt of tenders <SUP>9</SUP>
<SUP>9</SUP> please provide this information only if this notice is a _prior information notice_
```
	NOTICE TYPE="PRI" 
```

Question (for @muricna): **Is the identification of notice types (to chose the appropriate property, `epo:hasReceiptDeadline` or `epo:hasReceiptExpressionDeadline`) from above correct correct and complete?**

For reference here are **all** the notice types that can appear in forms F21, F22, and F23, based on our analysis of the test data and on previous findings in issue #238 :
```
Form F21:
<NOTICE TYPE="AWARD_CONTRACT"/>
<NOTICE TYPE="CONTRACT"/>
<NOTICE TYPE="PRI_ONLY"/>
<NOTICE TYPE="PRI_CALL_COMPETITION"/>

Form F22:
<NOTICE TYPE="AWARD_CONTRACT"/>
<NOTICE TYPE="CONTRACT"/>
<NOTICE TYPE="QSU_ONLY"/>
<NOTICE TYPE="QSU_CALL_COMPETITION"/>
<NOTICE TYPE="PER_ONLY"/>
<NOTICE TYPE="PER_CALL_COMPETITION"/>

Form F23:
<NOTICE TYPE="CONCESSION_AWARD_CONTRACT"/> 
<NOTICE TYPE="PRI"/>
```

Note: For valid `xsd:dateTime` formats please refer to: https://docstore.mik.ua/orelly/xml/schema/ch04_05.htm

**Comment by andreea-pasare** [comment]
In case of F23 we should map to epo:hasReceiptDeadline.

**Comment by csnyulas** [comment]
We discussed this issue in detail in an EPO meeting with @muricna and @costezki, and we arrived at the following conclusion:

The proposed mappings are fine, but in case of F22 they also cover a "gray area", where, according to the directives, there should be no data in the `DATE_RECEIPT_TENDERS` and `DATE_RECEIPT_TENDERS` elements, except if the forms were filled out inappropriately.

So, if we would map strictly only what it is explicitly mentioned in the forms, we would assign the xsd:dateTime value generated from the combination of date and time elements 
- to `epo:hasReceiptExpressionDeadline` property the following notice types: 
```
in F21:
    NOTICE TYPE="PRI_CALL_COMPETITION" 
in F22:
    NOTICE TYPE="PER_CALL_COMPETITION"
```
- and to `epo:hasReceiptDeadline` property the following notice types: 
```
in F21:
    NOTICE TYPE="CONTRACT" 
in F22:
    NOTICE TYPE="CONTRACT"
    NOTICE TYPE="QSU_CALL_COMPETITION"
in F23:
    NOTICE TYPE="PER_CALL_COMPETITION"
```

We should definitely **NOT** need to map the value of the date and time to either of those properties for the following notice types (as such information does not make sense, and most likely will not appear in any of the notices):
```
in F21:
    NOTICE TYPE="AWARD_CONTRACT" 
    NOTICE TYPE="PRI_ONLY"
in F22:
    NOTICE TYPE="AWARD_CONTRACT"
in F23:
    NOTICE TYPE="CONCESSION_AWARD_CONTRACT"
```

In the case of the following notice types, there should be no data present in the `DATE_RECEIPT_TENDERS` and `DATE_RECEIPT_TENDERS` elements, but in case there is (which would be against the prescription of the regulation), in order to not loose any data, we can map it to the  `epo:hasReceiptDeadline` property:
```
in F22:
    NOTICE TYPE="QSU_ONLY"
    NOTICE TYPE="PER_ONLY"
```

However, we should make a note both in the CM and TM, that these are just "safety" mappings, to cover "wrong" data, and are not really necessary.

**Comment by csnyulas** [comment]
Closing this issue as it has been fixed in the commits linked above, and the recommendation on documenting the noon-critical conditions have been also done in CM v.6.3.1.
