### ISSUE TITLE
Feedback F13, F20, F23 (issue 1): legal-basis of the Notice

### ISSUE THREAD

**Issue by csnyulas** [OP-TED/ted-rdf-mapping#349]
The metadata should map to the legal-basis of the Notice because that is what is in the xml and not the Procedure.

**Comment by costezki** [comment]
We can do the mapping now, as the same relation exists for the Notice class as well. 
![image](https://user-images.githubusercontent.com/13567133/235940824-5a9243df-22d0-4fb8-b01d-d80ff9cf0ff8.png)

**Comment by valexande** [comment]
Modifications have been applied to the TM in order to map the epo:hasLegalBasis with the epo:Notice

**Comment by csnyulas** [comment]
Conceptual model was also adjusted to reflect that the vale of the legal-basis is attached o the `epo:Notice` instance, through the `epo:hasLegalBasis` property (instead of the `epo:Procedure instance), starting with CM version 7.1.0. 

![image](https://user-images.githubusercontent.com/2441046/236123145-219d62bf-a130-4cad-93e4-17942ae808f2.png)

Some open questions related to this change (that perhaps @muricna could answer, or could be discussed):
- Does this mean that in the RDF data the `epo:Procedure` will never have the legal-basis set?
- How is the `epo:isBasedOnImplementingRegulation` property to be used? Wouldn't that be (more) appropriate (or at least in certain situations) to be used on the notice, as that represents the selection of the legal basis on the Standard Form, referring to the legal base on which the form used for that given notice was created?
- How about the LEGAL_BASIS_OTHER xml element, which at the moment is not mapped, as we don't have appropriate property and (controlled) value set? Would that also be added to the epo:Notice (and only to the Notice) later?
