### ISSUE TITLE
Feedback F13 (issue 2, CM): II.1.2.1 and II.2.2.2. not needed?

### ISSUE THREAD

**Issue by csnyulas** [OP-TED/ted-rdf-mapping#351]
II.1.2.1 and II.2.2.2. If there is no mapping why has a mapping been left in the conceptual mapping.

**Comment by csnyulas** [comment]
In fact I decided to keep the lines in the "Rules" sheet, but remove the mappings in the "Class path" and "Property path" columns, and keep only the Notes referring to the "Mapping Remarks" sheet, where more information is provided. This is similar to how we handle some other fields that are currently not mappable to EPO v.3.1.0, but might be in future versions.
@muricna do you agree with this approach?

I also did the same for fields `VII.1.1.1` and `VII.1.2.2`, which are about modifications related to Supplementary CPV codes in form F20.

All this is done in CM v.7.1.1

**Comment by muricna** [comment]
@csnyulas Where do I find CM v.7.1.1?

Please create a different ticket for F20
