### ISSUE TITLE
Feedback F13 (issue 4, CM): IV.1.0 Options are not included in F13

### ISSUE THREAD

**Issue by valexande** [OP-TED/ted-rdf-mapping#353]
IV.1.0 Options are not included in F13 so why is this mapping foreseen in the conceptual mapping, even more is that it maps to procedure.  However it does not seem to appear in the rdfs.

**Comment by csnyulas** [comment]
This is obviously wrong as it is, and I have removed that row from the conceptual mapping (starting with CM v.7.1.2)


The only thing I am wondering about is, what was the original intent in adding such a line there. 

![image](https://user-images.githubusercontent.com/2441046/236182400-9721b90e-d821-45dc-8b00-c0906743a77d.png)

_Is there any possible statement (possibly involving an `epo:ContractSpecificTerm` or `epo:ProcedureSpecificTerm`, and/or a boolean attribute) that would make sense to be always added about the Procedure related to "result of a design contest" notice (form F13)?_ Any ideas @muricna, @costezki or @andreea-pasare?

**Comment by valexande** [comment]
For this milestone this seems to be ok for closing, as the problem was to remove the row from the conceptual mapping.

I think we can re-open this in the future if there was a hidden intention.
