### ISSUE TITLE
Feedback F13 (issue 5, CM): IV.1.9 The mapping remarks does not say there is no mapping.

### ISSUE THREAD

**Issue by valexande** [OP-TED/ted-rdf-mapping#354]
IV.1.9 The mapping remarks does not say there is no mapping.  It should be noted this will be mappable with a future version of the ontology that includes summary of criterion.

**Comment by valexande** [comment]
We pointed this in the mapping remarks.

We state now that this specific concept is not mapable in the current version of the ontology

**Comment by csnyulas** [comment]
Actually the remark was added for the field `IV.1.9.0`, not the `IV.1.9`. This has been fixed in CM version `2.1.2-beta.1`, but it did not make it in tag `2.1.1-rc.1`.
