### ISSUE TITLE
Feedback F13 (issue 6, TM): Section V.0.4:  It is not clear why there are three empty rows.

### ISSUE THREAD

**Issue by valexande** [OP-TED/ted-rdf-mapping#355]
Section V.0.4:  It is not clear why there are three empty rows.
The fact that the contest is terminated without an award can be made by indicated epo:ProcurmentProcessInformation epo:isCompetitionTerminated in conjunction epo:hasAwardStatus …clos-nw which is in the rdf but not in the mapping

**Comment by csnyulas** [comment]
The reason for these three empty rows comes from the three rows providing mappings on `epo:Contract` and `epo:LotAwardOutcome` based on a similar question ("A concession/lot is awarded?") in F23 and F25. 
However, we did not know what would be the appropriate mapping in case of F13, where the question is "The contest was terminated without an award or attribution of prizes?" and the XPaths are `RESULTS/AWARDED_PRIZE`/`RESULTS/NO_AWARDED_PRIZE`. That's the reason for leaving the cells highlighted in yellow.

![image](https://user-images.githubusercontent.com/2441046/235858247-60624095-fd7a-415b-887b-33c139690844.png)

**Comment by valexande** [comment]
@csnyulas Maybe what Natalie is suggesting here for the second part " epo:ProcurmentProcessInformation epo:isCompetitionTerminated in conjunction epo:hasAwardStatus", is that maybe we should consider representing this information through epo:ProcurementProcessInformation. 

As the property epo:isCompetitionTerminated has the description: "No further contracts will be awarded in this procedure. Additional Information: This can be instantiated in the post award phase. PIN for Competition needs to be signaled. This field can be used even if no contracts are awarded in the contract award notice. This corresponds in eForms to BT-756 PIN Competition Termination."

Moreover, epo:ProcurementProcessInformation is connected with an epo:Lot through epo:concernsLot, and as I can understand epo:Contract is connected with an epo:Lot with epo:includesLot.

**Comment by csnyulas** [comment]
Clarification from @muricna : Use two mappings to express the fact that the competition is terminated (Xpath: `RESULTS/NO_AWARDED_PRIZE`):
![image](https://github.com/OP-TED/ted-rdf-mapping/assets/2441046/a355d064-ceb2-47f8-a931-a7cf105fc547)


![image](https://github.com/OP-TED/ted-rdf-mapping/assets/2441046/4e0409f9-17fb-43f0-a03d-63a1bb6b7b97)

and one mapping when the competition was NOT terminated (Xpath: `RESULTS/AWARDED_PRIZE`):

![image](https://github.com/OP-TED/ted-rdf-mapping/assets/2441046/d9eb8ca5-8e34-4be3-8bb7-c102d30c289a)

**Comment by csnyulas** [comment]
CM (v 2.1.1-beta.2) was also updated to reflect the changes:
![image](https://github.com/OP-TED/ted-rdf-mapping/assets/2441046/c4f37631-1096-43d4-a68b-9ba12ca03861)
