### ISSUE TITLE
Feedback F13 (issue 13, CM): No Direct Match for the Currency

### ISSUE THREAD

**Issue by valexande** [OP-TED/ted-rdf-mapping#362]
V.3.4.1.1 Why is it written there is no direct match for the currency

**Comment by valexande** [comment]
About this one I found that V.3.4.1 has a reference to the currency apart form the amount value. Please check the image below 
![2](https://user-images.githubusercontent.com/53187315/235739105-9c553fc5-5a68-4644-9a94-bfc9bb76cbac.png)

This can be verified also through some notices, as for example the notice 287682-2021 has this as concept 
![1](https://user-images.githubusercontent.com/53187315/235739372-ca43d5bb-934d-47e4-89a3-008ce5803e35.png)

So I am not sure why we should change the CM, unless I am missing something...

**Comment by muricna** [comment]
ok I see the "no direct match" is in the column C which is about the eforms.  Columns C and D should be hidden.  Therefore please ignores this comment.
