### ISSUE TITLE
Feedback F20 (issue 3, TM): Νo relation between ContractModificationNotice and AgentInRole 

### ISSUE THREAD

**Issue by valexande** [OP-TED/ted-rdf-mapping#364]
All sections: There is no relation between ContractModificationNotice and AgentInRole so no Organisations can be mapped unless a path can be found via  another path ie the Contract that is being modified that is related to the Lot?

**Comment by muricna** [comment]
This actually affects Section I, V, VI and VII

**Comment by valexande** [comment]
See #411 please

**Comment by csnyulas** [comment]
Closing this as it has been fixed and tested according to the solution presented in #411 (see referenced commits) and CM was also updated (in v.2.1.1-beta.6).

Note that some `epo:contextualisedBy` relationships might be missing from CM, in cases where there was no `epo:announcesRole` present in the CM for other forms (e.g. in case of Winners).
