### ISSUE TITLE
Feedback F20 (issue 5, TM): No relation between ContractModificationNotica and AgentInRole (DUPLICATE)

### ISSUE THREAD

**Issue by valexande** [OP-TED/ted-rdf-mapping#366]
Section II.2 There is no relation between ContractModificationNotica and AgentInRole unles the path is taken through Procedure has ProcurementScopeDividedIntoLots.

**Comment by csnyulas** [comment]
(almost) identical to #364

**Comment by valexande** [comment]
Duplicate with #364 which is closed
