### ISSUE TITLE
Feedback F20 (issue 7, TM):  II.2.7.4 Two elements under this field

### ISSUE THREAD

**Issue by valexande** [OP-TED/ted-rdf-mapping#368]
II.2.7.4 There is no mention anywhere that there is no mapping for the two elements under this field

**Comment by csnyulas** [comment]
A note should be added for now. Double check first with @andreea-pasare and/or @costezki that indeed there is no mapping possible for this (at least not into EPO v 3.1.0). Also check TM whether we have done any mapping related to this (unlikely)

**Comment by valexande** [comment]
I have asked @andreea-pasare for this if they are not mapable in this version of ePo.

In the TM they are not found

**Comment by valexande** [comment]
Talked with over it @andreea-pasare this is not mapable in the current version of ePo, but is planned for next release. Therefore, I will tag it as feature request

**Comment by csnyulas** [comment]
Reopening this issue, as it will needed to be dealt with, when we upgrade to newer version of EPO.

Comments were added to the CM (v.7.2.5), to mark that these fields are not mappable, yet, to EPO.

**Comment by valexande** [comment]
This issue is related to #417 which is considered as non mappable, thus I will close this one.
