### ISSUE TITLE
Feedback F23 CAN (issue 4, TM): Section V Heading through LotAwardOutcome describesLot 

### ISSUE THREAD

**Issue by valexande** [OP-TED/ted-rdf-mapping#375]
Section V: The section heading shows the section going through LotAwardOutcome describesLot however some of the fields seem to go through Contract which is a bit strange as there is no sign of signature in this notice.

**Comment by csnyulas** [comment]
Related to #408

**Comment by valexande** [comment]
Currently the Contract concept was removed from F23 and F25 and will be mapped in next version of ePO (probably v4.0). 

But even if the Contract would still exist, the TM and CM did not seem to have an actual problem, it was that in some cases the Property and Class path in the CM would start from epo:Contract and in others from epo:LotAwardOutcome.

We have harmonized the CM and this will be tackled.
