### ISSUE TITLE
Feedback F23 CAN (issue 10, CM): V.2.2.6 Notes do not redirect to the Mapping Remarks sheet

### ISSUE THREAD

**Issue by valexande** [OP-TED/ted-rdf-mapping#380]
V.2.2.6 Why do the notes not redirect to the Mapping Remarks sheet

**Comment by csnyulas** [comment]
Indeed, in addition to the information currently provided in the Notes field, we can also add a reference to "Mapping Remarks" sheet, where there is more information available about the handling of this field.

Also, make sure that the line for field V.2.2.6is included in the "Mapping Remarks" sheet of F23 (currently not checked).

**Comment by csnyulas** [comment]
As of version 7.0.2 of the CM, we 
- added also a reference to "Mapping Remarks" from the Notes field and
- included the missing line in the "Mapping Remarks" sheet for the field V.2.2.6 and XPATH `AWARD_CONTRACT/AWARDED_CONTRACT/CONTRACTORS/NO_AWARDED_TO_GROUP` in form F23 (previously was not present in F23, but only for other forms) 

![image](https://user-images.githubusercontent.com/2441046/235884743-3dd68997-1a7b-420f-86b9-d29e912b1c2d.png)
