### ISSUE TITLE
Feedback F23 CAN (issue 11, CM): Section V.2.3 why does the CL1 Controlled list of Roles

### ISSUE THREAD

**Issue by valexande** [OP-TED/ted-rdf-mapping#381]
Section V.2.3 why does the CL1 Controlled list of Roles refer to AgentInRole == winner (AWARDED_CONTRACT) and not (AWARDED_CONTRACT/CONTRACTORS in a similar way to the other roles

**Comment by csnyulas** [comment]
Update CL1 Controlled List of Roles to be more explicit/appropriate, and consistent among all forms.

**Comment by valexande** [comment]
The CM was updated as indicated, we shall close this one
