### ISSUE TITLE
Feedback F23 CAN (issue 12, CM): V.2.3.12 is out of contex

### ISSUE THREAD

**Issue by valexande** [OP-TED/ted-rdf-mapping#382]
The Row below V.2.3.12 is out of context it should probably be part of V.2.3.12 and should probably be the first part.

**Comment by csnyulas** [comment]
Suggestion has been implemented in CM version 7.0.1 an later

![image](https://user-images.githubusercontent.com/2441046/235879004-c7ea9dcd-40cb-4bd2-8001-285ecd1a73b7.png)

We also included the missing line in the "Mapping Remarks" sheet for the field V.2.3.12 and XPATH `AWARD_CONTRACT/AWARDED_CONTRACT/CONTRACTORS/CONTRACTOR/NO_SME` in form F23 (previously was not present in F23, but only for other forms)
