### ISSUE TITLE
Feedback F13, F20, F23 CAN (issue 13 from F23 CAN, TM): V.2.4.3-V.2.5 Checking of values assigned to Awarded Value

### ISSUE THREAD

**Issue by valexande** [OP-TED/ted-rdf-mapping#383]
V.2.4.3-V.2.5  Although the model allows for the mapping it should be checked with DG GROW whether these value are not rather an awarded value on the Lot award outcome rather than an estimate on the Tender.

**Comment by muricna** [comment]
No change. Keep as is associated to the Tender
