### ISSUE TITLE
Feedback F23 CAN (issue 16, TM): VI.4.3 This should be via the Procedur

### ISSUE THREAD

**Issue by valexande** [OP-TED/ted-rdf-mapping#386]
VI.4.3 This should be via the Procedure and not the lot this section covers the procedure

**Comment by valexande** [comment]
Modification to the mapping mechanism were performed to move this property to the Procedure

**Comment by csnyulas** [comment]
Conceptual mapping was also updated accordingly, starting with CM version 7.2.0

![image](https://user-images.githubusercontent.com/2441046/236186381-3600d042-3064-4f18-a10f-db06f41deef8.png)
