### ISSUE TITLE
Feedback F23 PIN (issue 6, CM): II.1.2.1 and II.2.2.2 remove from CM

### ISSUE THREAD

**Issue by valexande** [OP-TED/ted-rdf-mapping#393]
II.1.2.1 and II.2.2.2.If there is no mapping why has a mapping been left in the conceptual mapping.

**Comment by valexande** [comment]
@csnyulas Both II.1.2.1 and II.1.2.2 are not being mapped in the TM but we also do not have a class/property mapping on these in the CM.

Should I remove the row?

**Comment by csnyulas** [comment]
See (identical) issue https://github.com/OP-TED/ted-rdf-mapping/issues/351, where this has been addressed, and for any remaining open question.
