### ISSUE TITLE
Replace `epo:Notice epo:announcesRole` with `epo:AgentInRole epo:contextualisedBy`

### ISSUE THREAD

**Issue by csnyulas** [OP-TED/ted-rdf-mapping#412]
Do not use `epo:announcesRole` to refer to Buyer,  Winner, Mediator, TenderReceiver etc. roles. Instead use the `epo:contextualisedBy` property to link the various roles to the Procedure (which is referred to by the Notice through the `epo:refersToProcedure` property).

![image](https://github.com/OP-TED/ted-rdf-mapping/assets/2441046/3cca5c9c-37dd-4ea3-8b11-44f6f0fefb13)

**Note:** In future versions of EPO there might be additional properties that are more appropriate to link roles to Notice or Procedure. So, the solution suggested in this issue might be partially superseded with more appropriate, or form specific, mappings (e.g. we might want to use `epo:refersToRole` for certain forms and roles).

**Important:** This is a generic issue that would affect the mappings of all the standard forms. For a more restricted version of this, specific to F20, please see #411 .

**Comment by muricna** [comment]
Please only change F20 at this point of time we will consider the other forms at a later date this needs to be discussed in the working group

**Comment by valexande** [comment]
This issue seems duplicate with #411 which is closed and thus I will close this one also
