### ISSUE TITLE
F20: Change IRI generation pattern for the `epo:ContractModification` instances

### ISSUE THREAD

**Issue by csnyulas** [OP-TED/ted-rdf-mapping#419]
The notice level modification information, originating from section **VII.2.** of form F20, are encoded as instances of the `epo:ContractModification` class, according to the EPO (v.3.1.0) model:

![image](https://github.com/OP-TED/ted-rdf-mapping/assets/2441046/94503d73-f90d-4741-a181-ac6af24e1a5f)

In the screenshot below one can see a sample transformation of the notice level modification information:
![image](https://github.com/OP-TED/ted-rdf-mapping/assets/2441046/9c90fe6b-c4e6-424c-ab42-5fafb4c580f9)

In this screenshot the IRI of the instance of the `epo:ContractModification` class is:
`http://data.europa.eu/a4g/resource/id_2016-S-040-064434_ContractModification_NUqDzwkVVVUgZ2MjF797AY`
, which follows our generic template of:
_TED_RESOURCE_NAMESPACE_`/id_`_NOTICE_ID_`_`_CLASS_NAME_`_`_INSTANCE_HASH_

It was suggested by @muricna that it would make more sense to use in the IRI, instead of `ContractModification`, which currently coincides with the class name, something that better describes what this instance actually is. It was suggested that we use `ContractNoticeModification`, but perhaps a more appropriate, although definitely not nicer, name would be `ContractModificationNoticeModification` or `ContractModificationNoticeDescription`.

I agree that currently the `epo:ContractModification` instance names do not reflect properly the purpose of the instances, but they, at least, follow the pattern that we use for instances of other classes, and are in sync with the class name. I think the main problem is that the name of the EPO class is not appropriate, but we can't change that.

**So, the question is, how important is to change these instance names? Could the current name be considered acceptable? If we need to change it, what would be the best name to go with (from the multiple alternatives)?**

**Comment by costezki** [comment]
I propose to use `ContractModificationNoticeDescription` to be the most explicit.

**Comment by valexande** [comment]
This issues is closed as we decided to keep the ContractModification in the IRI. 

Additionally, note that the proposed solution will not be considered.

**Comment by csnyulas** [comment]
The solution, and the generated output has been checked, and it is correct (note that the last commit contains some changes that are related to a different issue , 418, but it does not affect the output)
