### ISSUE TITLE
x1.1.delta: Conceptual Mappings: Section I.1.12.1 Main Address (URL): Should not be through the contact point

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#96]
I think the main address URL should be of the organisation not the contact point.

**Comment by muricna** [comment]
However note 2705 suggest otherwise as the main internet address is the same for all Buyers.  In this example the first Buyer is the region and the other buyers are organisations within the region.  
This maybe needs to be checked with other examples.

**Comment by costezki** [comment]
We can discuss this in the ontology working group.

**Comment by csnyulas** [comment]
We have no control over what information will be filled as the main URL of the organization (sometimes it might be the URL of the website of the organization, other times the URL of the contact point). It is safer to map the main URL to the contact point's address, as we might be wrong if we map it to the organizations main URL.

**Comment by muricna** [comment]
As discussed in the WG of 10/01/2023 this should be the internet address of the organisation
