### ISSUE TITLE
x1.1.delta: Conceptual Mappings: Section I.2.1 Can not assume that there is no joint procurement

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#98]
In the forms indicating joint procurement is not compulsory so if it is not in the xml it does not exclude that joint procurement does not exist.  Therefore for example in 163-2021 we cannot assume joint procurement does not occur.  Joint procurement cannot be calculated by having many buyers in the procedure see recital 71 of the Directive 2014/24/EU:

Joint procurement can take many different forms, ranging from coordinated procurement through the preparation of common technical specifications for works, supplies or services that will be procured by a number of contracting authorities, each conducting a separate procurement procedure, to situations where the contracting authorities concerned jointly conduct one procurement procedure either by acting together or by entrusting one contracting authority with the management of the procurement procedure on behalf of all contracting authorities.

The field in xml is not a compulsory field so we may draw no conclusions except that joint procurement occurs if it is indicated

I would suggest the mapping from the xml is: if true then in rdf it is also true but if not mentioned in the xml then it should not be mentioned in the rdf

**Comment by costezki** [comment]
Similar to #102

**Comment by csnyulas** [comment]
Another way to see the difference provided by the fix that addresses this issue is to run the following query
```
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
SELECT * {
  ?s epo:isAwardedByCPB ?v 
}
```
 on both the `package_F03` repository (https://agraph.staging.ted-data.eu/#/repositories/package_F03/query)
and the `package_F03_tx11delta` repository in AllegroGraph staging server (https://agraph.staging.ted-data.eu/#/repositories/package_F03_tx11delta/query
