### ISSUE TITLE
x1.1.delta:Where can authority table mappings be found?

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#99]
In the package/transformation/resources the json files of the authority tables can be found but they are the full authority tables from EU Vocabularies, however the forms do not necessarily use all the concepts found in EU Vocabularies.

For example if we take :

-  buyer-legal-type for F03 we only use 6 concepts of the  22 concepts in EU Vocabularies.
-  main-activity for F03 we only use 10 concepts out of 21 concepts in EU Vocabularies ( and in other forms the concepts that will be used will be different.

**Comment by muricna** [comment]
For the country codes we the code for Kosovo does not seem to be used in the json file, the useage of Kosovo is foreseen for the TED schema see: 
![image](https://user-images.githubusercontent.com/26601116/186882012-7e69ad16-1da5-4869-a487-1760c27e9848.png)

**Comment by muricna** [comment]
The mapping to procurement-procedure-type also seems to be missing

**Comment by muricna** [comment]
In the json file for contract-nature there is the concept "combined" which is not used in the xml, nor is the element that is being mapped to shown.  It needs to be clearly shown how the mappings to the authority tables are to be understood.

**Comment by muricna** [comment]
winner-selection-status is not in the resources

**Comment by muricna** [comment]
All authority tables used in the mapping should be clearly mapped.

**Comment by costezki** [comment]
All resource files contain clear mapping from the "code" to a corresponding URI. Most of them are coming from the EU-Vocabularies. Some of them have been manually developed. 

In the conceptual mapping, the correspondence is clearly indicated. For example, the image below shows that the concept <.../all-rej> is mapped and it is found in the table at-voc:non-award-justification.

![image](https://user-images.githubusercontent.com/13567133/188220899-0eb32795-f4a1-41b8-9f8c-d8e0b48db2b4.png)

Shall a human-readable representation of these mappings be needed, we can provide it in the future, in a dedicated request. This, however, is outside the scope of the current project.

**Comment by costezki** [comment]
We will ensure that the mapping `resources` are available in the mapping suite.

**Comment by csnyulas** [comment]
We created a dedicated page in the TED Developers doc, to document of the code list mappings :
https://docs.ted.europa.eu/rdf-mapping/code-list-resources.html

This page is also referenced from the initial landing page the "XML to RDF Mappings" documentation: https://docs.ted.europa.eu/rdf-mapping/index.html
